minigod:
  config:
    # 权限密钥失效时间 s
    authCode.expireSecond: 7200 # 2*60*60
    # 用户token失效时间 s
    userToken.expireSecond: 7200 # 2*60*60
  cubp:
    isRemote: true
    url: http://10.1.2.99:6888/bpm
  openAccount:
    isVerifyFromCubp: true
    isVerifyIdCardFromThird: true
    isVerifyBankCardFromThird: true
    isVerifyWirthCa: true
    isVerifyOpenData: true
    validConfidence: 90
    images:
      app:
        type: 101,102,201,301,302,401
        count: 6
        apply: 101,102,201,301,302,401,601,602,603
      h5:
        type: 101,102,301,401,402,501,502,503,504,505
        count: 5
        apply: 101,102,201,301,302,401,402,501,502,503,504,505,601,602,603
  tencentApi:
    isRemote: true
    region: ap-guangzhou
    secretId: AKIDwc4HEUuuzrY1FGtcS5ThgRwZxFI4Zvzp
    secretKey: 3seBShhX8G91g7KH2X1IZbImHZaNtGON
  szca:
    isRemote: true
    orgName: 深圳CA
    orgCode: 723038758
    applyType: 2
    tokenType: 0
    url: http://218.17.161.11:18008
    getToken: /SecuritiesAccount/service/reqGetToKenService
    getCert: /SecuritiesAccount/service/reqGetCertDN
    getPDFInfoForSign: /SecuritiesAccount/service/reqGetPDFInfoForSign
    getCertApplyP10: /SecuritiesAccount/service/reqNACertApplyP10Service
    getSignP7ForPdf: /SecuritiesAccount/service/reqSignP7ForPdf
  proxy:
    isSyncOpen: false
    host: http://10.1.2.99:8901/securities
    checkUser: /test/checkUser
    syncData: /checkUser


