minigod:
  config:
    # 权限密钥失效时间 s
    authCode.expireSecond: 7200 # 2*60*60
    # 用户token失效时间 s
    userToken.expireSecond: 7200 # 2*60*60
  bpm:
    isRemote: true
    url: http://192.168.1.251:8900/bpm
  openAccount:
    isVerifyFromBpm: true
    isVerifyIdCardFromThird: false
    isVerifyBankCardFromThird: false
    isVerifyLiveFaceFromThird: false
    isVerifyWithCa: true
    isVerifyOpenData: true
    validLiveScore: 85
    validConfidence: 70
    images:
      idCardCn: 101,102
      idCardHk: 103
      idCardHkTemp: 103,105
      idCardPassport: 104
      bankCard: 201
      address: 604
      signature: 301
      avatar: 401,402,501,502,503,504,505
      cnH5ImageCount: 6
  tencentApi:
    region: ap-guangzhou
    secretId: AKIDwc4HEUuuzrY1FGtcS5ThgRwZxFI4Zvzp
    secretKey: 3seBShhX8G91g7KH2X1IZbImHZaNtGON
  szca:
    orgName: 深圳CA
    orgCode: 723038758
    applyType: 2
    tokenType: 0
    url: http://218.17.161.11:18008
    getToken: /SecuritiesAccount/service/reqGetToKenService
    getCert: /SecuritiesAccount/service/reqGetCertDN
    getPDFInfoForSign: /SecuritiesAccount/service/reqGetPDFInfoForSign
    getCertApplyP10: /SecuritiesAccount/service/reqNACertApplyP10Service
    getSignP7ForPdf: /SecuritiesAccount/service/reqSignP7ForPdf
  jfszca:
    userName: admin01
    userPwd: AF_88888888
    url: https://sns.9fstock.com:9008
    login: /platform_api/org_login
    getToken: /platform_api/get_ca_token
    getCert: /platform_api/get_ca_cert_dn
    getPDFInfoForSign: /platform_api/get_pdf_for_sign
    getCertApplyP10: /platform_api/get_ca_cert_apply
    getSignP7ForPdf: /platform_api/sign_p7_for_pdf
  proxy:
    isSyncOpen: false
    host: http://uat.zszhizhu.com:17000
    checkUser: /user_api/fetch_user_info
    syncHost: http://uat.zszhizhu.com:17000/web_app
    syncData: /open_api/update_open_user_info


