minigod:
  config:
    # 权限密钥失效时间 s
    authCode.expireSecond: 7200 # 2*60*60
    # 用户token失效时间 s
    userToken.expireSecond: 7200 # 2*60*60
  cubp:
    isRemote: true
    url: http://10.1.2.99:7777/cubp
  openAccount:
    isVerifyFromCubp: true
    isVerifyIdCardFromThird: true
    isVerifyBankCardFromThird: true
    isVerifyLiveFaceFromThird: true
    isVerifyWithCa: false
    isVerifyOpenData: true
    validLiveScore: 85
    validConfidence: 70
    images:
      idCardCn: 101,102
      idCardHk: 103
      idCardHkTemp: 103,105
      idCardPassport: 104
      bankCard: 201
      signature: 301
      avatar: 401,402,501,502,503,504,505
      cnH5ImageCount: 6
      cnAppImageCount: 5
  tencentApi:
    region: ap-guangzhou
    secretId: AKIDwc4HEUuuzrY1FGtcS5ThgRwZxFI4Zvzp
    secretKey: 3seBShhX8G91g7KH2X1IZbImHZaNtGON
  szca:
    orgName: 深圳CA
    orgCode: 723038758
    applyType: 2
    tokenType: 0
    url: http://218.17.161.11:18008
    getToken: /SecuritiesAccount/service/reqGetToKenService
    getCert: /SecuritiesAccount/service/reqGetCertDN
    getPDFInfoForSign: /SecuritiesAccount/service/reqGetPDFInfoForSign
    getCertApplyP10: /SecuritiesAccount/service/reqNACertApplyP10Service
    getSignP7ForPdf: /SecuritiesAccount/service/reqSignP7ForPdf
  proxy:
    isSyncOpen: true
    host: http://uat2.zszhizhu.com:7000
    checkUser: /user_api/fetch_user_info
    syncHost: http://uat2.zszhizhu.com:9003
    syncData: /open_api/update_open_user_info



