# Tomcat
server:
  port: 8900
  servlet:
    context-path: /bpm

spring:
  # 环境 dev|test|pro
  profiles:
    active: dev

  http:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources: # 静态资源的路径
    static-locations: classpath:/statics/,classpath:/views/
  velocity:
    resource-loader-path: classpath:/template/
    charset: UTF-8


  #JSP视图解析器
  # 页面默认前缀目录
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

# APP模块
jwt:
  # token 加密秘钥
  secret: 3733b9170b1e4994bddcf1ce62c4c082
  # token有效时长，7天，单位秒
  expire: 604800
  header: token



# 日志配置
logging:
  config:
    classpath: logback-spring.xml

#activeMQ
activemq:
  broker-url: tcp://10.1.2.99:61616
  user: admin
  password: admin
  #true 表示使用内置的MQ，false则连接服务器
  in-memory: false
  pool:
    #true表示使用连接池；false时，每发送一条数据创建一个连接
    enabled: false
    #连接池最大连接数
    max-connections: 10
    #空闲的连接过期时间，默认为30秒
    idle-timeout: 30000
    #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0
    expiry-timeout: 0
debug: true