spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.140:3306/mg_main?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/mg_main?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username:  root
    password:  zz@123
#    password:  1234

# Mybatis配置
mybatis:
  mapper-locations: classpath*:com/minigod/*/mapper/*/*.xml