spring:
  profiles:
    active: db-dev, redis-dev, notify-dev, storage-dev, account-dev, task
  messages:
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8902
  servlet:
    context-path:

logging:
  level:
    root:  DEBUG
    org.springframework:  DEBUG
    org.mybatis:  DEBUG
    com.zsdp.loan.core:  ERROR
    com.zsdp.loan.db:  ERROR
    com.zsdp.loan.admin:  DEBUG
    com.zsdp.loan.app:  ERROR
    com.zsdp.loan:  ERROR

