minigod:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: tencent
    # 本地对象存储配置信息
    local:
      storagePath: /data/apps/datas
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://10.1.2.99:8901/security/storage/file/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: minigod
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDwc4HEUuuzrY1FGtcS5ThgRwZxFI4Zvzp
      secretKey: 3seBShhX8G91g7KH2X1IZbImHZaNtGON
      region: ap-guangzhou
      bucketName: security-1258565443
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://pd5cb6ulu.bkt.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: minigod