package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TActGroupMember extends AbstractTable {

	static {
		init();
	}

	private TActGroupMember(){
		super.tableName = "act_group_member";
	}

	private TActGroupMember(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TActGroupMember getInstance() {
		return new TActGroupMember();
	}

	public static final TActGroupMember getInstance(String aliasName) {
		return new TActGroupMember(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("actGroupId", "act_group_id");
		allFieldMap.put("memberUserId", "member_user_id");
		allFieldMap.put("shareUserId", "share_user_id");
		allFieldMap.put("isLead", "is_lead");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> actGroupId = new TableFieldImpl<Integer>(this,"act_group_id","actGroupId","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> memberUserId = new TableFieldImpl<Integer>(this,"member_user_id","memberUserId","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> shareUserId = new TableFieldImpl<Integer>(this,"share_user_id","shareUserId","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isLead = new TableFieldImpl<Boolean>(this,"is_lead","isLead","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,actGroupId,memberUserId,shareUserId,isLead,createTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TActGroupMember[table=act_group_member]";
	}
}
