package com.minigod.persist.tables;

import com.minigod.db4j.table.*;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class TActivityUserPrivilegeExchange extends AbstractTable {

	static {
		init();
	}

	private TActivityUserPrivilegeExchange(){
		super.tableName = "activity_user_privilege_exchange";
	}

	private TActivityUserPrivilegeExchange(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TActivityUserPrivilegeExchange getInstance() {
		return new TActivityUserPrivilegeExchange();
	}

	public static final TActivityUserPrivilegeExchange getInstance(String aliasName) {
		return new TActivityUserPrivilegeExchange(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("privilegeCode", "privilege_code");
		allFieldMap.put("privilegeCodeValidTime", "privilege_code_valid_time");
		allFieldMap.put("isActivate", "is_activate");
		allFieldMap.put("isActivateTime", "is_activate_time");
		allFieldMap.put("isFreeCommision", "is_free_commision");
		allFieldMap.put("isFreeCommisionTime", "is_free_commision_time");
		allFieldMap.put("isValidL2Market", "is_valid_l2_market");
		allFieldMap.put("isValidL2MarketTime", "is_valid_l2_market_time");
		allFieldMap.put("phoneNumber", "phone_number");
		allFieldMap.put("activitySource", "activity_source");
		allFieldMap.put("recordStatus", "record_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 * 犇犇号 | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","犇犇号");

	/**
	 * 特权码 | varchar(50)
	 */
	public final TableField<String> privilegeCode = new TableFieldImpl<String>(this,"privilege_code","privilegeCode","特权码");

	/**
	 * 特权码有效时间 | datetime
	 */
	public final DateTableField<Date> privilegeCodeValidTime = new DateTableFieldImpl<Date>(this,"privilege_code_valid_time","privilegeCodeValidTime","特权码有效时间");

	/**
	 * 是否激活[0-否 1-是 2-未知] | int(1)
	 */
	public final TableField<Integer> isActivate = new TableFieldImpl<Integer>(this,"is_activate","isActivate","是否激活[0-否 1-是 2-未知]");

	/**
	 * 激活时间 | datetime
	 */
	public final DateTableField<Date> isActivateTime = new DateTableFieldImpl<Date>(this,"is_activate_time","isActivateTime","激活时间");

	/**
	 * 免佣是否生效[0-否 1-是 2-未知] | int(1)
	 */
	public final TableField<Integer> isFreeCommision = new TableFieldImpl<Integer>(this,"is_free_commision","isFreeCommision","免佣是否生效[0-否 1-是 2-未知]");

	/**
	 * 免佣生效时间 | datetime
	 */
	public final DateTableField<Date> isFreeCommisionTime = new DateTableFieldImpl<Date>(this,"is_free_commision_time","isFreeCommisionTime","免佣生效时间");

	/**
	 * L2行情是否生效[0-否 1-是 2-未知] | int(1)
	 */
	public final TableField<Integer> isValidL2Market = new TableFieldImpl<Integer>(this,"is_valid_l2_market","isValidL2Market","L2行情是否生效[0-否 1-是 2-未知]");

	/**
	 * L2行情生效时间 | datetime
	 */
	public final DateTableField<Date> isValidL2MarketTime = new DateTableFieldImpl<Date>(this,"is_valid_l2_market_time","isValidL2MarketTime","L2行情生效时间");

	/**
	 * 手机号码 | varchar(100)
	 */
	public final TableField<String> phoneNumber = new TableFieldImpl<String>(this,"phone_number","phoneNumber","手机号码");

	/**
	 * 来源 | varchar(100)
	 */
	public final TableField<String> activitySource = new TableFieldImpl<String>(this,"activity_source","activitySource","来源");

	/**
	 * 记录状态[0-无效 1-有效] | int(1)
	 */
	public final TableField<Integer> recordStatus = new TableFieldImpl<Integer>(this,"record_status","recordStatus","记录状态[0-无效 1-有效]");

	private final TableField<?>[] allFields = new TableField<?>[] {id,userId,privilegeCode,privilegeCodeValidTime,isActivate,isActivateTime,isFreeCommision,isFreeCommisionTime,isValidL2Market,isValidL2MarketTime,phoneNumber,activitySource,recordStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TActivityUserPrivilegeExchange[table=activity_user_privilege_exchange]";
	}
}
