package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TActGroup extends AbstractTable {

	static {
		init();
	}

	private TActGroup(){
		super.tableName = "act_group";
	}

	private TActGroup(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TActGroup getInstance() {
		return new TActGroup();
	}

	public static final TActGroup getInstance(String aliasName) {
		return new TActGroup(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("actGroupId", "act_group_id");
		allFieldMap.put("actGroupName", "act_group_name");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("memberNum", "member_num");
		allFieldMap.put("lockVersion", "lock_version");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"act_group_id","actGroupId","");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","");

	public final TableField<Integer> actGroupId = new TableFieldImpl<Integer>(this,"act_group_id","actGroupId","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> actGroupName = new TableFieldImpl<String>(this,"act_group_name","actGroupName","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> memberNum = new TableFieldImpl<Integer>(this,"member_num","memberNum","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","");

	private final TableField<?>[] allFields = new TableField<?>[] {actGroupId,actGroupName,userId,createTime,updateTime,memberNum,lockVersion,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TActGroup[table=act_group]";
	}
}
