package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TActivityUserIndex extends AbstractTable {

	static {
		init();
	}

	private TActivityUserIndex(){
		super.tableName = "activity_user_index";
	}

	private TActivityUserIndex(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TActivityUserIndex getInstance() {
		return new TActivityUserIndex();
	}

	public static final TActivityUserIndex getInstance(String aliasName) {
		return new TActivityUserIndex(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("actUserIndexId", "act_user_index_id");
		allFieldMap.put("mobile", "phone");
		allFieldMap.put("tradeday", "tradeday");
		allFieldMap.put("userIndex", "user_index");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 记录用户所猜指数ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"act_user_index_id","actUserIndexId","记录用户所猜指数ID");
	public final TableField<Integer> actUserIndexId = new TableFieldImpl<Integer>(this,"act_user_index_id","actUserIndexId","记录用户所猜指数ID");

	/**
	 *  | varchar(15)
	 */
	public final TableField<String> mobile = new TableFieldImpl<String>(this,"phone","phone","");

	/**
	 * 用户预测指数所属交易日 | date
	 */
	public final DateTableField<Date> tradeday = new DateTableFieldImpl<Date>(this,"tradeday","tradeday","用户预测指数所属交易日");

	/**
	 * 记录用户所猜指数 | decimal(10,2)
	 */
	public final TableField<Double> userIndex = new TableFieldImpl<Double>(this,"user_index","userIndex","记录用户所猜指数");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	/**
	 * 状态 0停用，1正常使用 | tinyint(4)
	 */
	public final TableField<Integer> isStatus = new TableFieldImpl<Integer>(this,"is_status","isStatus","状态 0停用，1正常使用");

	private final TableField<?>[] allFields = new TableField<?>[] {actUserIndexId,mobile,tradeday,userIndex,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TActivityUserIndex[table=activity_user_index]";
	}
}
