package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TActivityTemplate extends AbstractTable {

	static {
		init();
	}

	private TActivityTemplate(){
		super.tableName = "activity_template";
	}

	private TActivityTemplate(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TActivityTemplate getInstance() {
		return new TActivityTemplate();
	}

	public static final TActivityTemplate getInstance(String aliasName) {
		return new TActivityTemplate(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("atId", "at_id");
		allFieldMap.put("msgContent", "msg_content");
		allFieldMap.put("templateTitle", "template_title");
		allFieldMap.put("templateName", "template_name");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(20) unsigned
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"at_id","atId","");
	public final TableField<Integer> atId = new TableFieldImpl<Integer>(this,"at_id","atId","");

	/**
	 * 推送消息内容 | varchar(512)
	 */
	public final TableField<String> msgContent = new TableFieldImpl<String>(this,"msg_content","msgContent","推送消息内容");

	/**
	 * 系统通知模板标题 | varchar(128)
	 */
	public final TableField<String> templateTitle = new TableFieldImpl<String>(this,"template_title","templateTitle","系统通知模板标题");

	/**
	 * 系统通知模板名称 | varchar(128)
	 */
	public final TableField<String> templateName = new TableFieldImpl<String>(this,"template_name","templateName","系统通知模板名称");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	private final TableField<?>[] allFields = new TableField<?>[] {atId,msgContent,templateTitle,templateName,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TActivityTemplate[table=activity_template]";
	}
}
