package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdUserNiuReg extends AbstractTable {

	static {
		init();
	}

	private TAdUserNiuReg(){
		super.tableName = "ad_user_niu_reg";
	}

	private TAdUserNiuReg(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdUserNiuReg getInstance() {
		return new TAdUserNiuReg();
	}

	public static final TAdUserNiuReg getInstance(String aliasName) {
		return new TAdUserNiuReg(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("adId", "ad_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("type", "type");
		allFieldMap.put("targetId", "target_id");
		allFieldMap.put("createTime", "create_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 * 广告id | int(11)
	 */
	public final TableField<Integer> adId = new TableFieldImpl<Integer>(this,"ad_id","adId","广告id");

	/**
	 * 用户id | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * R-抽到红包，G-抽到金币，E-兑换奖品 | char(1)
	 */
	public final TableField<String> type = new TableFieldImpl<String>(this,"type","type","R-抽到红包，G-抽到金币，E-兑换奖品");

	/**
	 * 目标id(牛人活动中为牛人用户id,默认为0) | int(11)
	 */
	public final TableField<Integer> targetId = new TableFieldImpl<Integer>(this,"target_id","targetId","目标id(牛人活动中为牛人用户id,默认为0)");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,adId,userId,type,targetId,createTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdUserNiuReg[table=ad_user_niu_reg]";
	}
}
