package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserOrg extends AbstractTable {

	static {
		init();
	}

	private TAdviserOrg(){
		super.tableName = "adviser_org";
	}

	private TAdviserOrg(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserOrg getInstance() {
		return new TAdviserOrg();
	}

	public static final TAdviserOrg getInstance(String aliasName) {
		return new TAdviserOrg(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("adviserOrgId", "adviser_org_id");
		allFieldMap.put("orgType", "org_type");
		allFieldMap.put("orgName", "org_name");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("creVersion", "cre_version");
		allFieldMap.put("updVersion", "upd_version");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"adviser_org_id","adviserOrgId","");
	public final TableField<Integer> adviserOrgId = new TableFieldImpl<Integer>(this,"adviser_org_id","adviserOrgId","");

	/**
	 * 投顾机构类别(1： 表示证券公司;2： 表示证券投资咨询机构) | tinyint(4)
	 */
	public final TableField<Integer> orgType = new TableFieldImpl<Integer>(this,"org_type","orgType","投顾机构类别(1： 表示证券公司;2： 表示证券投资咨询机构)");

	/**
	 * 投顾机构的名称 | varchar(200)
	 */
	public final TableField<String> orgName = new TableFieldImpl<String>(this,"org_name","orgName","投顾机构的名称");

	/**
	 * 默认1有效，0无效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","默认1有效，0无效");

	/**
	 * 创建版本号 | int(11)
	 */
	public final TableField<Integer> creVersion = new TableFieldImpl<Integer>(this,"cre_version","creVersion","创建版本号");

	/**
	 * 修改版本号 | int(11)
	 */
	public final TableField<Integer> updVersion = new TableFieldImpl<Integer>(this,"upd_version","updVersion","修改版本号");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {adviserOrgId,orgType,orgName,isStatus,creVersion,updVersion,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserOrg[table=adviser_org]";
	}
}
