package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserViewpointLike extends AbstractTable {

	static {
		init();
	}

	private TAdviserViewpointLike(){
		super.tableName = "adviser_viewpoint_like";
	}

	private TAdviserViewpointLike(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserViewpointLike getInstance() {
		return new TAdviserViewpointLike();
	}

	public static final TAdviserViewpointLike getInstance(String aliasName) {
		return new TAdviserViewpointLike(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("likeId", "like_id");
		allFieldMap.put("viewpointId", "viewpoint_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"like_id","likeId","");
	public final TableField<Integer> likeId = new TableFieldImpl<Integer>(this,"like_id","likeId","");

	/**
	 * 观点id | bigint(11)
	 */
	public final TableField<Long> viewpointId = new TableFieldImpl<Long>(this,"viewpoint_id","viewpointId","观点id");

	/**
	 * 点赞用户id | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","点赞用户id");

	/**
	 * 记录状态 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {likeId,viewpointId,userId,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserViewpointLike[table=adviser_viewpoint_like]";
	}
}
