package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserRecommend extends AbstractTable {

	static {
		init();
	}

	private TAdviserRecommend(){
		super.tableName = "adviser_recommend";
	}

	private TAdviserRecommend(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserRecommend getInstance() {
		return new TAdviserRecommend();
	}

	public static final TAdviserRecommend getInstance(String aliasName) {
		return new TAdviserRecommend(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("arId", "ar_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("grade", "grade");
		allFieldMap.put("recommendDesc", "recommend_desc");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | int(20) unsigned
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"ar_id","arId","主键");
	public final TableField<Integer> arId = new TableFieldImpl<Integer>(this,"ar_id","arId","主键");

	/**
	 * 投顾用户id | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","投顾用户id");

	/**
	 * 排列顺序，数字越小越靠前显示，最小为1 | int(3)
	 */
	public final TableField<Integer> grade = new TableFieldImpl<Integer>(this,"grade","grade","排列顺序，数字越小越靠前显示，最小为1");

	/**
	 * 推荐简短介绍 | varchar(256)
	 */
	public final TableField<String> recommendDesc = new TableFieldImpl<String>(this,"recommend_desc","recommendDesc","推荐简短介绍");

	/**
	 * 状态	0-无效， 1-有效  | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","状态	0-无效， 1-有效 ");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {arId,userId,grade,recommendDesc,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserRecommend[table=adviser_recommend]";
	}
}
