package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserViewpointComment extends AbstractTable {

	static {
		init();
	}

	private TAdviserViewpointComment(){
		super.tableName = "adviser_viewpoint_comment";
	}

	private TAdviserViewpointComment(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserViewpointComment getInstance() {
		return new TAdviserViewpointComment();
	}

	public static final TAdviserViewpointComment getInstance(String aliasName) {
		return new TAdviserViewpointComment(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("commentId", "comment_id");
		allFieldMap.put("clientReqId", "client_req_id");
		allFieldMap.put("viewpointId", "viewpoint_id");
		allFieldMap.put("fromUser", "from_user");
		allFieldMap.put("toUser", "to_user");
		allFieldMap.put("content", "content");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 互动id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"comment_id","commentId","互动id");
	public final TableField<Integer> commentId = new TableFieldImpl<Integer>(this,"comment_id","commentId","互动id");

	/**
	 * 客户端防重发唯一id | varchar(50)
	 */
	public final TableField<String> clientReqId = new TableFieldImpl<String>(this,"client_req_id","clientReqId","客户端防重发唯一id");

	/**
	 * 观点id | bigint(11)
	 */
	public final TableField<Long> viewpointId = new TableFieldImpl<Long>(this,"viewpoint_id","viewpointId","观点id");

	/**
	 * 发表用户id | int(11)
	 */
	public final TableField<Integer> fromUser = new TableFieldImpl<Integer>(this,"from_user","fromUser","发表用户id");

	/**
	 * 回复用户id默认为0 | int(11)
	 */
	public final TableField<Integer> toUser = new TableFieldImpl<Integer>(this,"to_user","toUser","回复用户id默认为0");

	/**
	 * 互动内容 | varchar(500)
	 */
	public final TableField<String> content = new TableFieldImpl<String>(this,"content","content","互动内容");

	/**
	 * 记录状态(0-无效，1-有效) | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态(0-无效，1-有效)");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {commentId,clientReqId,viewpointId,fromUser,toUser,content,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserViewpointComment[table=adviser_viewpoint_comment]";
	}
}
