package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserViewpoint extends AbstractTable {

	static {
		init();
	}

	private TAdviserViewpoint(){
		super.tableName = "adviser_viewpoint";
	}

	private TAdviserViewpoint(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserViewpoint getInstance() {
		return new TAdviserViewpoint();
	}

	public static final TAdviserViewpoint getInstance(String aliasName) {
		return new TAdviserViewpoint(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("viewpointId", "viewpoint_id");
		allFieldMap.put("clientReqId", "client_req_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("viewpointType", "viewpoint_type");
		allFieldMap.put("busContent", "bus_content");
		allFieldMap.put("readNum", "read_num");
		allFieldMap.put("realReadNum", "real_read_num");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 观点id | bigint(11)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"viewpoint_id","viewpointId","观点id");
	public final TableField<Long> viewpointId = new TableFieldImpl<Long>(this,"viewpoint_id","viewpointId","观点id");

	/**
	 * 客户端防重发唯一编码 | varchar(50)
	 */
	public final TableField<String> clientReqId = new TableFieldImpl<String>(this,"client_req_id","clientReqId","客户端防重发唯一编码");

	/**
	 * 用户id | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * 观点类型(P-观点) | char(1)
	 */
	public final TableField<String> viewpointType = new TableFieldImpl<String>(this,"viewpoint_type","viewpointType","观点类型(P-观点)");

	/**
	 * 业务信息 | varchar(5000)
	 */
	public final TableField<String> busContent = new TableFieldImpl<String>(this,"bus_content","busContent","业务信息");

	/**
	 * 阅读数初始为0 | int(11)
	 */
	public final TableField<Integer> readNum = new TableFieldImpl<Integer>(this,"read_num","readNum","阅读数初始为0");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> realReadNum = new TableFieldImpl<Integer>(this,"real_read_num","realReadNum","");

	/**
	 * 观点状态(0-无效，1-有效) | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","观点状态(0-无效，1-有效)");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {viewpointId,clientReqId,userId,viewpointType,busContent,readNum,realReadNum,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserViewpoint[table=adviser_viewpoint]";
	}
}
