package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAdviserOpenInfo extends AbstractTable {

	static {
		init();
	}

	private TAdviserOpenInfo(){
		super.tableName = "adviser_open_info";
	}

	private TAdviserOpenInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAdviserOpenInfo getInstance() {
		return new TAdviserOpenInfo();
	}

	public static final TAdviserOpenInfo getInstance(String aliasName) {
		return new TAdviserOpenInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("adviserOpenId", "adviser_open_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("openActivity", "open_activity");
		allFieldMap.put("openBrokerage", "open_brokerage");
		allFieldMap.put("openPrivilege", "open_privilege");
		allFieldMap.put("openInstruction", "open_instruction");
		allFieldMap.put("openUrl", "open_url");
		allFieldMap.put("appIosPackage", "app_ios_package");
		allFieldMap.put("appAndroidPackage", "app_android_package");
		allFieldMap.put("channelParm", "channel_parm");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 自增长 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"adviser_open_id","adviserOpenId","自增长");
	public final TableField<Integer> adviserOpenId = new TableFieldImpl<Integer>(this,"adviser_open_id","adviserOpenId","自增长");

	/**
	 * 投顾用户id | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","投顾用户id");

	/**
	 * 开户活动 | varchar(1000)
	 */
	public final TableField<String> openActivity = new TableFieldImpl<String>(this,"open_activity","openActivity","开户活动");

	/**
	 * 开户佣金 | varchar(200)
	 */
	public final TableField<String> openBrokerage = new TableFieldImpl<String>(this,"open_brokerage","openBrokerage","开户佣金");

	/**
	 * 开户专享特权,以|分隔符保存起来，获取直接以数组形式给前端 | varchar(500)
	 */
	public final TableField<String> openPrivilege = new TableFieldImpl<String>(this,"open_privilege","openPrivilege","开户专享特权,以|分隔符保存起来，获取直接以数组形式给前端");

	/**
	 * 开户说明 | varchar(2000)
	 */
	public final TableField<String> openInstruction = new TableFieldImpl<String>(this,"open_instruction","openInstruction","开户说明");

	/**
	 * 开户链接 | varchar(200)
	 */
	public final TableField<String> openUrl = new TableFieldImpl<String>(this,"open_url","openUrl","开户链接");

	/**
	 * ios包名 | varchar(100)
	 */
	public final TableField<String> appIosPackage = new TableFieldImpl<String>(this,"app_ios_package","appIosPackage","ios包名");

	/**
	 * android包名 | varchar(100)
	 */
	public final TableField<String> appAndroidPackage = new TableFieldImpl<String>(this,"app_android_package","appAndroidPackage","android包名");

	/**
	 * 渠道参数标识，追加到open_url后面 | varchar(30)
	 */
	public final TableField<String> channelParm = new TableFieldImpl<String>(this,"channel_parm","channelParm","渠道参数标识，追加到open_url后面");

	/**
	 * 0-无效，默认1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，默认1-有效");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {adviserOpenId,userId,openActivity,openBrokerage,openPrivilege,openInstruction,openUrl,appIosPackage,appAndroidPackage,channelParm,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAdviserOpenInfo[table=adviser_open_info]";
	}
}
