package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TAppDownloadCount extends AbstractTable {

	static {
		init();
	}

	private TAppDownloadCount(){
		super.tableName = "app_download_count";
	}

	private TAppDownloadCount(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TAppDownloadCount getInstance() {
		return new TAppDownloadCount();
	}

	public static final TAppDownloadCount getInstance(String aliasName) {
		return new TAppDownloadCount(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("channelId", "channel_Id");
		allFieldMap.put("downloadCount", "download_count");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updatedTime", "updated_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 渠道ID | varchar(50)
	 */
	public final TableField<String>  pk = new TableFieldImpl<String>(this,"channel_Id","channelId","渠道ID");
	public final TableField<String> channelId = new TableFieldImpl<String>(this,"channel_Id","channelId","渠道ID");

	/**
	 * 下载次数统计 | int(10)
	 */
	public final TableField<Integer> downloadCount = new TableFieldImpl<Integer>(this,"download_count","downloadCount","下载次数统计");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updatedTime = new DateTableFieldImpl<Date>(this,"updated_time","updatedTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {channelId,downloadCount,createTime,updatedTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TAppDownloadCount[table=app_download_count]";
	}
}
