package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TBrokerDepositInfo extends AbstractTable {

	static {
		init();
	}

	private TBrokerDepositInfo(){
		super.tableName = "broker_deposit_info";
	}

	private TBrokerDepositInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TBrokerDepositInfo getInstance() {
		return new TBrokerDepositInfo();
	}

	public static final TBrokerDepositInfo getInstance(String aliasName) {
		return new TBrokerDepositInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("brkDepositId", "brk_deposit_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("brkCustid", "brk_custid");
		allFieldMap.put("depositAcc", "deposit_acc");
		allFieldMap.put("depositAccType", "deposit_acc_type");
		allFieldMap.put("isDefault", "is_default");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 资金账户id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"brk_deposit_id","brkDepositId","资金账户id");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","资金账户id");

	public final TableField<Integer> brkDepositId = new TableFieldImpl<Integer>(this,"brk_deposit_id","brkDepositId","资金账户id");

	/**
	 * 用户id | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * 券商id | int(11)
	 */
	public final TableField<Integer> brokerId = new TableFieldImpl<Integer>(this,"broker_id","brokerId","券商id");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> brkCustid = new TableFieldImpl<String>(this,"brk_custid","brkCustid","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> depositAcc = new TableFieldImpl<String>(this,"deposit_acc","depositAcc","");

	/**
	 * 资金账号类型 | char(1)
	 */
	public final TableField<String> depositAccType = new TableFieldImpl<String>(this,"deposit_acc_type","depositAccType","资金账号类型");

	/**
	 * 是否主资金账号 | tinyint(1)
	 */
	public final TableField<Boolean> isDefault = new TableFieldImpl<Boolean>(this,"is_default","isDefault","是否主资金账号");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 最后修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","最后修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {brkDepositId,userId,brokerId,brkCustid,depositAcc,depositAccType,isDefault,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TBrokerDepositInfo[table=broker_deposit_info]";
	}
}
