package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TCashFrozenScheduler extends AbstractTable {

	static {
		init();
	}

	private TCashFrozenScheduler(){
		super.tableName = "cash_frozen_scheduler";
	}

	private TCashFrozenScheduler(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TCashFrozenScheduler getInstance() {
		return new TCashFrozenScheduler();
	}

	public static final TCashFrozenScheduler getInstance(String aliasName) {
		return new TCashFrozenScheduler(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("cashFrozenId", "cash_frozen_id");
		allFieldMap.put("frozenTrxId", "frozen_trx_id");
		allFieldMap.put("accountId", "account_id");
		allFieldMap.put("frozenType", "frozen_type");
		allFieldMap.put("frozenDate", "frozen_date");
		allFieldMap.put("frzAmount", "frz_amount");
		allFieldMap.put("unfrozenSrcTransId", "unfrozen_src_trans_id");
		allFieldMap.put("unfrozenTrxId", "unfrozen_trx_id");
		allFieldMap.put("examine", "examine");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 冻结id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"cash_frozen_id","cashFrozenId","冻结id");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","冻结id");

	public final TableField<Integer> cashFrozenId = new TableFieldImpl<Integer>(this,"cash_frozen_id","cashFrozenId","冻结id");

	/**
	 * 冻结的交易ID | int(11)
	 */
	public final TableField<Integer> frozenTrxId = new TableFieldImpl<Integer>(this,"frozen_trx_id","frozenTrxId","冻结的交易ID");

	/**
	 * 账户ID | int(11)
	 */
	public final TableField<Integer> accountId = new TableFieldImpl<Integer>(this,"account_id","accountId","账户ID");

	/**
	 *  | char(1)
	 */
	public final TableField<String> frozenType = new TableFieldImpl<String>(this,"frozen_type","frozenType","");

	/**
	 * 解冻日期 | date
	 */
	public final DateTableField<Date> frozenDate = new DateTableFieldImpl<Date>(this,"frozen_date","frozenDate","解冻日期");

	/**
	 * 冻结金额 | decimal(16,2)
	 */
	public final TableField<BigDecimal> frzAmount = new TableFieldImpl<BigDecimal>(this,"frz_amount","frzAmount","冻结金额");

	/**
	 * 源系统客户端交易ID | varchar(23)
	 */
	public final TableField<String> unfrozenSrcTransId = new TableFieldImpl<String>(this,"unfrozen_src_trans_id","unfrozenSrcTransId","源系统客户端交易ID");

	/**
	 * 解冻的交易ID | int(11)
	 */
	public final TableField<Integer> unfrozenTrxId = new TableFieldImpl<Integer>(this,"unfrozen_trx_id","unfrozenTrxId","解冻的交易ID");

	/**
	 * 是否已审批 | char(1)
	 */
	public final TableField<String> examine = new TableFieldImpl<String>(this,"examine","examine","是否已审批");

	/**
	 * 状态(0停用,默认1正常使用) | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","状态(0停用,默认1正常使用)");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {cashFrozenId,frozenTrxId,accountId,frozenType,frozenDate,frzAmount,unfrozenSrcTransId,unfrozenTrxId,examine,isStatus,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TCashFrozenScheduler[table=cash_frozen_scheduler]";
	}
}
