package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TCashTrans extends AbstractTable {

	static {
		init();
	}

	private TCashTrans(){
		super.tableName = "cash_trans";
	}

	private TCashTrans(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TCashTrans getInstance() {
		return new TCashTrans();
	}

	public static final TCashTrans getInstance(String aliasName) {
		return new TCashTrans(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("transactionId", "transaction_id");
		allFieldMap.put("srcSys", "src_sys");
		allFieldMap.put("srcBus", "src_bus");
		allFieldMap.put("srcTransId", "src_trans_id");
		allFieldMap.put("md5", "md5");
		allFieldMap.put("accountDate", "account_date");
		allFieldMap.put("relaTransactionId", "rela_transaction_id");
		allFieldMap.put("reverseFlag", "reverse_flag");
		allFieldMap.put("reverseTransaction", "reverse_transaction");
		allFieldMap.put("remark", "remark");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 交易请求Id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"transaction_id","transactionId","交易请求Id");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","交易请求Id");

	public final TableField<Integer> transactionId = new TableFieldImpl<Integer>(this,"transaction_id","transactionId","交易请求Id");

	/**
	 * 请求来源系统 | char(3)
	 */
	public final TableField<String> srcSys = new TableFieldImpl<String>(this,"src_sys","srcSys","请求来源系统");

	/**
	 * 请求来源业务 | char(6)
	 */
	public final TableField<String> srcBus = new TableFieldImpl<String>(this,"src_bus","srcBus","请求来源业务");

	/**
	 * 源系统客户端交易ID | varchar(23)
	 */
	public final TableField<String> srcTransId = new TableFieldImpl<String>(this,"src_trans_id","srcTransId","源系统客户端交易ID");

	/**
	 * 请求数据摘要 | char(32)
	 */
	public final TableField<String> md5 = new TableFieldImpl<String>(this,"md5","md5","请求数据摘要");

	/**
	 * 记账日期 | date
	 */
	public final DateTableField<Date> accountDate = new DateTableFieldImpl<Date>(this,"account_date","accountDate","记账日期");

	/**
	 * 业务关联的交易请求 | int(11)
	 */
	public final TableField<Integer> relaTransactionId = new TableFieldImpl<Integer>(this,"rela_transaction_id","relaTransactionId","业务关联的交易请求");

	/**
	 * 冲账标志 | char(1)
	 */
	public final TableField<String> reverseFlag = new TableFieldImpl<String>(this,"reverse_flag","reverseFlag","冲账标志");

	/**
	 * 冲账关联交易ID | int(11)
	 */
	public final TableField<Integer> reverseTransaction = new TableFieldImpl<Integer>(this,"reverse_transaction","reverseTransaction","冲账关联交易ID");

	/**
	 * 备注 | varchar(512)
	 */
	public final TableField<String> remark = new TableFieldImpl<String>(this,"remark","remark","备注");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {transactionId,srcSys,srcBus,srcTransId,md5,accountDate,relaTransactionId,reverseFlag,reverseTransaction,remark,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TCashTrans[table=cash_trans]";
	}
}
