package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TCouponTemplate extends AbstractTable {

	static {
		init();
	}

	private TCouponTemplate(){
		super.tableName = "coupon_template";
	}

	private TCouponTemplate(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TCouponTemplate getInstance() {
		return new TCouponTemplate();
	}

	public static final TCouponTemplate getInstance(String aliasName) {
		return new TCouponTemplate(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("templateId", "template_id");
		allFieldMap.put("title", "title");
		allFieldMap.put("description", "description");
		allFieldMap.put("type", "type");
		allFieldMap.put("unit", "unit");
		allFieldMap.put("denomination", "denomination");
		allFieldMap.put("interestAddDay", "interest_add_day");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | int(20) unsigned
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"template_id","templateId","主键");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","主键");

	public final TableField<Integer> templateId = new TableFieldImpl<Integer>(this,"template_id","templateId","主键");

	/**
	 * 卡券标题 | varchar(32)
	 */
	public final TableField<String> title = new TableFieldImpl<String>(this,"title","title","卡券标题");

	/**
	 * 卡券描述 | varchar(128)
	 */
	public final TableField<String> description = new TableFieldImpl<String>(this,"description","description","卡券描述");

	/**
	 * 卡券类型，1:加息券 | int(11)
	 */
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","卡券类型，1:加息券");

	/**
	 * 卡券单位，如 加息券 在界面上要显示 “2%”那么这里就配置 “%”，代金券要显示“5元“那么这里就配置”元 | varchar(8)
	 */
	public final TableField<String> unit = new TableFieldImpl<String>(this,"unit","unit","卡券单位，如 加息券 在界面上要显示 “2%”那么这里就配置 “%”，代金券要显示“5元“那么这里就配置”元");

	/**
	 * 卡券面值，与卡券类型一一对应，如果是加息券，不超过1.0000 | decimal(5,4)
	 */
	public final TableField<BigDecimal> denomination = new TableFieldImpl<BigDecimal>(this,"denomination","denomination","卡券面值，与卡券类型一一对应，如果是加息券，不超过1.0000");

	/**
	 * 有效天数：与加息券相关，可以用于加息的天数 | int(11)
	 */
	public final TableField<Integer> interestAddDay = new TableFieldImpl<Integer>(this,"interest_add_day","interestAddDay","有效天数：与加息券相关，可以用于加息的天数");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {templateId,title,description,type,unit,denomination,interestAddDay,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TCouponTemplate[table=coupon_template]";
	}
}
