package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TDistributeSaveTmp extends AbstractTable {

	static {
		init();
	}

	private TDistributeSaveTmp(){
		super.tableName = "distribute_save_tmp";
	}

	private TDistributeSaveTmp(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TDistributeSaveTmp getInstance() {
		return new TDistributeSaveTmp();
	}

	public static final TDistributeSaveTmp getInstance(String aliasName) {
		return new TDistributeSaveTmp(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("userId", "userId");
		allFieldMap.put("info", "info");
		allFieldMap.put("step", "step");
		allFieldMap.put("type", "type");
		allFieldMap.put("name", "name");
		allFieldMap.put("createdTime", "created_time");
		allFieldMap.put("updatedTime", "updated_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 用户ID | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"userId","userId","用户ID");

	/**
	 * 字符串信息 | varchar(500)
	 */
	public final TableField<String> info = new TableFieldImpl<String>(this,"info","info","字符串信息");

	/**
	 * 步骤 | int(20)
	 */
	public final TableField<Integer> step = new TableFieldImpl<Integer>(this,"step","step","步骤");

	/**
	 * 功能标识 | int(20)
	 */
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","功能标识");

	/**
	 * 功能名称 | varchar(20)
	 */
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","功能名称");

	/**
	 * 创建时间 | date
	 */
	public final DateTableField<Date> createdTime = new DateTableFieldImpl<Date>(this,"created_time","createdTime","创建时间");

	/**
	 * 修改时间 | date
	 */
	public final DateTableField<Date> updatedTime = new DateTableFieldImpl<Date>(this,"updated_time","updatedTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {id,userId,info,step,type,name,createdTime,updatedTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TDistributeSaveTmp[table=distribute_save_tmp]";
	}
}
