package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TDivAllotReservation extends AbstractTable {

	static {
		init();
	}

	private TDivAllotReservation(){
		super.tableName = "div_allot_reservation";
	}

	private TDivAllotReservation(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TDivAllotReservation getInstance() {
		return new TDivAllotReservation();
	}

	public static final TDivAllotReservation getInstance(String aliasName) {
		return new TDivAllotReservation(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("resvId", "resv_id");
		allFieldMap.put("taskDate", "task_date");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("finishStatus", "finish_status");
		allFieldMap.put("finishTime", "finish_time");
		allFieldMap.put("errMsg", "err_msg");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 预订ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"resv_id","resvId","预订ID");
	public final TableField<Integer> resvId = new TableFieldImpl<Integer>(this,"resv_id","resvId","预订ID");

	/**
	 * 任务日期 | date
	 */
	public final DateTableField<Date> taskDate = new DateTableFieldImpl<Date>(this,"task_date","taskDate","任务日期");

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");

	/**
	 * 结束状态 | char(1)
	 */
	public final TableField<String> finishStatus = new TableFieldImpl<String>(this,"finish_status","finishStatus","结束状态");

	/**
	 * 结束时间 | datetime
	 */
	public final DateTableField<Date> finishTime = new DateTableFieldImpl<Date>(this,"finish_time","finishTime","结束时间");

	/**
	 *  | varchar(500)
	 */
	public final TableField<String> errMsg = new TableFieldImpl<String>(this,"err_msg","errMsg","");

	private final TableField<?>[] allFields = new TableField<?>[] {resvId,taskDate,ptfId,finishStatus,finishTime,errMsg};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TDivAllotReservation[table=div_allot_reservation]";
	}
}
