package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TExtResponse extends AbstractTable {

	static {
		init();
	}

	private TExtResponse(){
		super.tableName = "ext_response";
	}

	private TExtResponse(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TExtResponse getInstance() {
		return new TExtResponse();
	}

	public static final TExtResponse getInstance(String aliasName) {
		return new TExtResponse(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("responseId", "response_id");
		allFieldMap.put("responseValue", "response_value");
		allFieldMap.put("createTime", "create_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"response_id","responseId","主键");
	public final TableField<Integer> responseId = new TableFieldImpl<Integer>(this,"response_id","responseId","主键");

	/**
	 * 外部系统返回信息 | mediumtext
	 */
	public final TableField<String> responseValue = new TableFieldImpl<String>(this,"response_value","responseValue","外部系统返回信息");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {responseId,responseValue,createTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TExtResponse[table=ext_response]";
	}
}
