package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TFeatTaskConfig extends AbstractTable {

	static {
		init();
	}

	private TFeatTaskConfig(){
		super.tableName = "feat_task_config";
	}

	private TFeatTaskConfig(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TFeatTaskConfig getInstance() {
		return new TFeatTaskConfig();
	}

	public static final TFeatTaskConfig getInstance(String aliasName) {
		return new TFeatTaskConfig(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("featTaskConfigId", "feat_task_config_id");
		allFieldMap.put("featId", "feat_id");
		allFieldMap.put("featTaskName", "feat_task_name");
		allFieldMap.put("featValue", "feat_value");
		allFieldMap.put("featTaskDesc", "feat_task_desc");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"feat_task_config_id","featTaskConfigId","");
	public final TableField<Integer> featTaskConfigId = new TableFieldImpl<Integer>(this,"feat_task_config_id","featTaskConfigId","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> featId = new TableFieldImpl<Integer>(this,"feat_id","featId","");

	/**
	 * 任务名称 | varchar(50)
	 */
	public final TableField<String> featTaskName = new TableFieldImpl<String>(this,"feat_task_name","featTaskName","任务名称");

	/**
	 * 功勋值 | int(11)
	 */
	public final TableField<Integer> featValue = new TableFieldImpl<Integer>(this,"feat_value","featValue","功勋值");

	/**
	 * 任务描述 | varchar(1000)
	 */
	public final TableField<String> featTaskDesc = new TableFieldImpl<String>(this,"feat_task_desc","featTaskDesc","任务描述");

	private final TableField<?>[] allFields = new TableField<?>[] {featTaskConfigId,featId,featTaskName,featValue,featTaskDesc};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TFeatTaskConfig[table=feat_task_config]";
	}
}
