package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TFeatLevel extends AbstractTable {

	static {
		init();
	}

	private TFeatLevel(){
		super.tableName = "feat_level";
	}

	private TFeatLevel(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TFeatLevel getInstance() {
		return new TFeatLevel();
	}

	public static final TFeatLevel getInstance(String aliasName) {
		return new TFeatLevel(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("featLevelId", "feat_level_id");
		allFieldMap.put("featId", "feat_id");
		allFieldMap.put("featLevel", "feat_level");
		allFieldMap.put("featLevelStart", "feat_level_start");
		allFieldMap.put("featLevelEnd", "feat_level_end");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"feat_level_id","featLevelId","");
	public final TableField<Integer> featLevelId = new TableFieldImpl<Integer>(this,"feat_level_id","featLevelId","");

	/**
	 * 功勋id | int(11)
	 */
	public final TableField<Integer> featId = new TableFieldImpl<Integer>(this,"feat_id","featId","功勋id");

	/**
	 * 等级 | int(11)
	 */
	public final TableField<Integer> featLevel = new TableFieldImpl<Integer>(this,"feat_level","featLevel","等级");

	/**
	 * 功勋等级开始值 | int(11)
	 */
	public final TableField<Integer> featLevelStart = new TableFieldImpl<Integer>(this,"feat_level_start","featLevelStart","功勋等级开始值");

	/**
	 * 功勋等级结束值 | int(11)
	 */
	public final TableField<Integer> featLevelEnd = new TableFieldImpl<Integer>(this,"feat_level_end","featLevelEnd","功勋等级结束值");

	private final TableField<?>[] allFields = new TableField<?>[] {featLevelId,featId,featLevel,featLevelStart,featLevelEnd};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TFeatLevel[table=feat_level]";
	}
}
