package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TFileDownload extends AbstractTable {

	static {
		init();
	}

	private TFileDownload(){
		super.tableName = "file_download";
	}

	private TFileDownload(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TFileDownload getInstance() {
		return new TFileDownload();
	}

	public static final TFileDownload getInstance(String aliasName) {
		return new TFileDownload(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("fileName", "file_name");
		allFieldMap.put("downloadUrl", "download_url");
		allFieldMap.put("busyType", "busy_type");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 文件名称 | varchar(100)
	 */
	public final TableField<String> fileName = new TableFieldImpl<String>(this,"file_name","fileName","文件名称");

	/**
	 * 文件路径 | varchar(250)
	 */
	public final TableField<String> downloadUrl = new TableFieldImpl<String>(this,"download_url","downloadUrl","文件路径");

	/**
	 * 业务类型 | int(11)
	 */
	public final TableField<Integer> busyType = new TableFieldImpl<Integer>(this,"busy_type","busyType","业务类型");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,fileName,downloadUrl,busyType,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TFileDownload[table=file_download]";
	}
}
