package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TFprdChannel extends AbstractTable {

	static {
		init();
	}

	private TFprdChannel(){
		super.tableName = "fprd_channel";
	}

	private TFprdChannel(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TFprdChannel getInstance() {
		return new TFprdChannel();
	}

	public static final TFprdChannel getInstance(String aliasName) {
		return new TFprdChannel(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("fprdChannelId", "fprd_channel_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("channelId", "channel_id");
		allFieldMap.put("sequence", "sequence");
		allFieldMap.put("qnOpenid", "qn_openid");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 理财用户渠道ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"fprd_channel_id","fprdChannelId","理财用户渠道ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","理财用户渠道ID");

	public final TableField<Integer> fprdChannelId = new TableFieldImpl<Integer>(this,"fprd_channel_id","fprdChannelId","理财用户渠道ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 渠道ID | int(11)
	 */
	public final TableField<Integer> channelId = new TableFieldImpl<Integer>(this,"channel_id","channelId","渠道ID");

	/**
	 * 绑定序号 | int(11)
	 */
	public final TableField<Integer> sequence = new TableFieldImpl<Integer>(this,"sequence","sequence","绑定序号");

	/**
	 * 齐牛OPENID | varchar(50)
	 */
	public final TableField<String> qnOpenid = new TableFieldImpl<String>(this,"qn_openid","qnOpenid","齐牛OPENID");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {fprdChannelId,userId,channelId,sequence,qnOpenid,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TFprdChannel[table=fprd_channel]";
	}
}
