package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TFprdCurrencyAccelerate extends AbstractTable {

	static {
		init();
	}

	private TFprdCurrencyAccelerate(){
		super.tableName = "fprd_currency_accelerate";
	}

	private TFprdCurrencyAccelerate(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TFprdCurrencyAccelerate getInstance() {
		return new TFprdCurrencyAccelerate();
	}

	public static final TFprdCurrencyAccelerate getInstance(String aliasName) {
		return new TFprdCurrencyAccelerate(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("currencyAccelerateId", "currency_accelerate_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("startDate", "start_date");
		allFieldMap.put("endDate", "end_date");
		allFieldMap.put("rate", "rate");
		allFieldMap.put("couponId", "coupon_id");
		allFieldMap.put("extCouponId", "ext_coupon_id");
		allFieldMap.put("sendStatus", "send_status");
		allFieldMap.put("errorMsg", "error_msg");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 加息id,主键，自增长字段 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"currency_accelerate_id","currencyAccelerateId","加息id,主键，自增长字段");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","加息id,主键，自增长字段");

	public final TableField<Integer> currencyAccelerateId = new TableFieldImpl<Integer>(this,"currency_accelerate_id","currencyAccelerateId","加息id,主键，自增长字段");

	/**
	 * 加息用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","加息用户ID");

	/**
	 * 加息开始日期 | date
	 */
	public final DateTableField<Date> startDate = new DateTableFieldImpl<Date>(this,"start_date","startDate","加息开始日期");

	/**
	 * 加息结束日期 | date
	 */
	public final DateTableField<Date> endDate = new DateTableFieldImpl<Date>(this,"end_date","endDate","加息结束日期");

	/**
	 * 加息额度 | decimal(5,4)
	 */
	public final TableField<BigDecimal> rate = new TableFieldImpl<BigDecimal>(this,"rate","rate","加息额度");

	/**
	 * 使用对应的卡券ID | int(11)
	 */
	public final TableField<Integer> couponId = new TableFieldImpl<Integer>(this,"coupon_id","couponId","使用对应的卡券ID");

	/**
	 * 外部返回的卡券ID | varchar(16)
	 */
	public final TableField<String> extCouponId = new TableFieldImpl<String>(this,"ext_coupon_id","extCouponId","外部返回的卡券ID");

	/**
	 * 发送状态	W:等待E:错误U:未知（或异常）S:成功 | char(1)
	 */
	public final TableField<String> sendStatus = new TableFieldImpl<String>(this,"send_status","sendStatus","发送状态	W:等待E:错误U:未知（或异常）S:成功");

	/**
	 * 错误信息 | varchar(256)
	 */
	public final TableField<String> errorMsg = new TableFieldImpl<String>(this,"error_msg","errorMsg","错误信息");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {currencyAccelerateId,userId,startDate,endDate,rate,couponId,extCouponId,sendStatus,errorMsg,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TFprdCurrencyAccelerate[table=fprd_currency_accelerate]";
	}
}
