package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGameFightJoin extends AbstractTable {

	static {
		init();
	}

	private TGameFightJoin(){
		super.tableName = "game_fight_join";
	}

	private TGameFightJoin(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGameFightJoin getInstance() {
		return new TGameFightJoin();
	}

	public static final TGameFightJoin getInstance(String aliasName) {
		return new TGameFightJoin(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("fightJoinId", "fight_join_id");
		allFieldMap.put("fightEventId", "fight_event_id");
		allFieldMap.put("gameUserId", "game_user_id");
		allFieldMap.put("latestGuessId", "latest_guess_id");
		allFieldMap.put("maxWinNum", "max_win_num");
		allFieldMap.put("rank", "rank");
		allFieldMap.put("status", "status");
		allFieldMap.put("endType", "end_type");
		allFieldMap.put("lockVersion", "lock_version");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 一战到底用户参赛表 参赛id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"fight_join_id","fightJoinId","一战到底用户参赛表 参赛id");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","一战到底用户参赛表 参赛id");

	public final TableField<Integer> fightJoinId = new TableFieldImpl<Integer>(this,"fight_join_id","fightJoinId","一战到底用户参赛表 参赛id");

	/**
	 * 赛事id | int(11)
	 */
	public final TableField<Integer> fightEventId = new TableFieldImpl<Integer>(this,"fight_event_id","fightEventId","赛事id");

	/**
	 * 参与人id | int(11)
	 */
	public final TableField<Integer> gameUserId = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","参与人id");

	/**
	 * 最新的竞猜id | int(11)
	 */
	public final TableField<Integer> latestGuessId = new TableFieldImpl<Integer>(this,"latest_guess_id","latestGuessId","最新的竞猜id");

	/**
	 * 连胜次数 | int(11)
	 */
	public final TableField<Integer> maxWinNum = new TableFieldImpl<Integer>(this,"max_win_num","maxWinNum","连胜次数");

	/**
	 * 排名 | int(11)
	 */
	public final TableField<Integer> rank = new TableFieldImpl<Integer>(this,"rank","rank","排名");

	/**
	 * 用户参赛状态 1进行中 9结束 | tinyint(4)
	 */
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","用户参赛状态 1进行中 9结束");

	/**
	 * 结束类型 猜错0 猜对1，即得冠军赛事结束 缺席2 | tinyint(4)
	 */
	public final TableField<Integer> endType = new TableFieldImpl<Integer>(this,"end_type","endType","结束类型 猜错0 猜对1，即得冠军赛事结束 缺席2");

	/**
	 * 乐观锁 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {fightJoinId,fightEventId,gameUserId,latestGuessId,maxWinNum,rank,status,endType,lockVersion,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TGameFightJoin[table=game_fight_join]";
	}
}
