package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGameFightGuess extends AbstractTable {

	static {
		init();
	}

	private TGameFightGuess(){
		super.tableName = "game_fight_guess";
	}

	private TGameFightGuess(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGameFightGuess getInstance() {
		return new TGameFightGuess();
	}

	public static final TGameFightGuess getInstance(String aliasName) {
		return new TGameFightGuess(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("fightGuessId", "fight_guess_id");
		allFieldMap.put("fightEventId", "fight_event_id");
		allFieldMap.put("gameUserId", "game_user_id");
		allFieldMap.put("guessDate", "guess_date");
		allFieldMap.put("guessValue", "guess_value");
		allFieldMap.put("isRight", "is_right");
		allFieldMap.put("lockVersion", "lock_version");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 竞猜记录表 竞猜id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"fight_guess_id","fightGuessId","竞猜记录表 竞猜id");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","竞猜记录表 竞猜id");

	public final TableField<Integer> fightGuessId = new TableFieldImpl<Integer>(this,"fight_guess_id","fightGuessId","竞猜记录表 竞猜id");

	/**
	 * 赛事id | int(11)
	 */
	public final TableField<Integer> fightEventId = new TableFieldImpl<Integer>(this,"fight_event_id","fightEventId","赛事id");

	/**
	 * 参与人id | int(11)
	 */
	public final TableField<Integer> gameUserId = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","参与人id");

	/**
	 * 竞猜日期 竞猜哪一个交易日涨或跌 | date
	 */
	public final DateTableField<Date> guessDate = new DateTableFieldImpl<Date>(this,"guess_date","guessDate","竞猜日期 竞猜哪一个交易日涨或跌");

	/**
	 * 竞猜值 跌0 涨1 | tinyint(4)
	 */
	public final TableField<Integer> guessValue = new TableFieldImpl<Integer>(this,"guess_value","guessValue","竞猜值 跌0 涨1");

	/**
	 * 是否正确 错误0 正确1 | tinyint(4)
	 */
	public final TableField<Integer> isRight = new TableFieldImpl<Integer>(this,"is_right","isRight","是否正确 错误0 正确1");

	/**
	 * 乐观锁 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {fightGuessId,fightEventId,gameUserId,guessDate,guessValue,isRight,lockVersion,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TGameFightGuess[table=game_fight_guess]";
	}
}
