package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGameFightStatistics extends AbstractTable {

	static {
		init();
	}

	private TGameFightStatistics(){
		super.tableName = "game_fight_statistics";
	}

	private TGameFightStatistics(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGameFightStatistics getInstance() {
		return new TGameFightStatistics();
	}

	public static final TGameFightStatistics getInstance(String aliasName) {
		return new TGameFightStatistics(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("gameUserId", "game_user_id");
		allFieldMap.put("maxWinNum", "max_win_num");
		allFieldMap.put("curWinNum", "cur_win_num");
		allFieldMap.put("winUpdateTime", "win_update_time");
		allFieldMap.put("rightNum", "right_num");
		allFieldMap.put("rightUpdateTime", "right_update_time");
		allFieldMap.put("wrongNum", "wrong_num");
		allFieldMap.put("joinNum", "join_num");
		allFieldMap.put("lockVersion", "lock_version");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","");

	public final TableField<Integer> gameUserId = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","");

	/**
	 * 最大连胜次数 | int(11)
	 */
	public final TableField<Integer> maxWinNum = new TableFieldImpl<Integer>(this,"max_win_num","maxWinNum","最大连胜次数");

	/**
	 * 当前连胜次数 | int(11)
	 */
	public final TableField<Integer> curWinNum = new TableFieldImpl<Integer>(this,"cur_win_num","curWinNum","当前连胜次数");

	/**
	 * 连胜次数更新时间 | datetime
	 */
	public final DateTableField<Date> winUpdateTime = new DateTableFieldImpl<Date>(this,"win_update_time","winUpdateTime","连胜次数更新时间");

	/**
	 * 猜对次数 | int(11)
	 */
	public final TableField<Integer> rightNum = new TableFieldImpl<Integer>(this,"right_num","rightNum","猜对次数");

	/**
	 * 猜对次数更新时间 | datetime
	 */
	public final DateTableField<Date> rightUpdateTime = new DateTableFieldImpl<Date>(this,"right_update_time","rightUpdateTime","猜对次数更新时间");

	/**
	 * 猜错次数 | int(11)
	 */
	public final TableField<Integer> wrongNum = new TableFieldImpl<Integer>(this,"wrong_num","wrongNum","猜错次数");

	/**
	 * 总参与竞猜次数 | int(11)
	 */
	public final TableField<Integer> joinNum = new TableFieldImpl<Integer>(this,"join_num","joinNum","总参与竞猜次数");

	/**
	 * 乐观锁 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {gameUserId,maxWinNum,curWinNum,winUpdateTime,rightNum,rightUpdateTime,wrongNum,joinNum,lockVersion,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TGameFightStatistics[table=game_fight_statistics]";
	}
}
