package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGameStkInfo extends AbstractTable {

	static {
		init();
	}

	private TGameStkInfo(){
		super.tableName = "game_stk_info";
	}

	private TGameStkInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGameStkInfo getInstance() {
		return new TGameStkInfo();
	}

	public static final TGameStkInfo getInstance(String aliasName) {
		return new TGameStkInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("gameStkId", "game_stk_id");
		allFieldMap.put("clientReqId", "client_req_id");
		allFieldMap.put("gameEventId", "game_event_id");
		allFieldMap.put("gameUserId", "game_user_id");
		allFieldMap.put("assetId", "asset_id");
		allFieldMap.put("cfmPrice", "cfm_price");
		allFieldMap.put("exchangeCode", "exchange_code");
		allFieldMap.put("induCode", "indu_code");
		allFieldMap.put("reason", "reason");
		allFieldMap.put("rank", "rank");
		allFieldMap.put("yield", "yield");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"game_stk_id","gameStkId","");
	public final TableField<Integer> gameStkId = new TableFieldImpl<Integer>(this,"game_stk_id","gameStkId","");

	/**
	 * 请求唯一id | varchar(50)
	 */
	public final TableField<String> clientReqId = new TableFieldImpl<String>(this,"client_req_id","clientReqId","请求唯一id");

	/**
	 * 赛事id | int(11)
	 */
	public final TableField<Integer> gameEventId = new TableFieldImpl<Integer>(this,"game_event_id","gameEventId","赛事id");

	/**
	 * 参与人id | int(11)
	 */
	public final TableField<Integer> gameUserId = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","参与人id");

	/**
	 * 资产id | varchar(20)
	 */
	public final TableField<String> assetId = new TableFieldImpl<String>(this,"asset_id","assetId","资产id");

	/**
	 * 成交价格 | decimal(10,4)
	 */
	public final TableField<Double> cfmPrice = new TableFieldImpl<Double>(this,"cfm_price","cfmPrice","成交价格");

	/**
	 * 所属指数 | varchar(10)
	 */
	public final TableField<String> exchangeCode = new TableFieldImpl<String>(this,"exchange_code","exchangeCode","所属指数");

	/**
	 * 所属行业 | int(11)
	 */
	public final TableField<Integer> induCode = new TableFieldImpl<Integer>(this,"indu_code","induCode","所属行业");

	/**
	 * 推荐理由 | varchar(100)
	 */
	public final TableField<String> reason = new TableFieldImpl<String>(this,"reason","reason","推荐理由");

	/**
	 * 比赛排名 | int(11)
	 */
	public final TableField<Integer> rank = new TableFieldImpl<Integer>(this,"rank","rank","比赛排名");

	/**
	 * 最终盈亏比例 | decimal(10,4)
	 */
	public final TableField<Double> yield = new TableFieldImpl<Double>(this,"yield","yield","最终盈亏比例");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {gameStkId,clientReqId,gameEventId,gameUserId,assetId,cfmPrice,exchangeCode,induCode,reason,rank,yield,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGameStkInfo[table=game_stk_info]";
	}
}
