package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGameEventInfo extends AbstractTable {

	static {
		init();
	}

	private TGameEventInfo(){
		super.tableName = "game_event_info";
	}

	private TGameEventInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGameEventInfo getInstance() {
		return new TGameEventInfo();
	}

	public static final TGameEventInfo getInstance(String aliasName) {
		return new TGameEventInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("gameEventId", "game_event_id");
		allFieldMap.put("clientReqId", "client_req_id");
		allFieldMap.put("gameUserId", "game_user_id");
		allFieldMap.put("eventName", "event_name");
		allFieldMap.put("startTime", "start_time");
		allFieldMap.put("endTime", "end_time");
		allFieldMap.put("limitNum", "limit_num");
		allFieldMap.put("num", "num");
		allFieldMap.put("eventStatus", "event_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"game_event_id","gameEventId","");
	public final TableField<Integer> gameEventId = new TableFieldImpl<Integer>(this,"game_event_id","gameEventId","");

	/**
	 * 请求唯一id | varchar(50)
	 */
	public final TableField<String> clientReqId = new TableFieldImpl<String>(this,"client_req_id","clientReqId","请求唯一id");

	/**
	 * 发起人id | int(11)
	 */
	public final TableField<Integer> gameUserId = new TableFieldImpl<Integer>(this,"game_user_id","gameUserId","发起人id");

	/**
	 * 赛事名称 | varchar(20)
	 */
	public final TableField<String> eventName = new TableFieldImpl<String>(this,"event_name","eventName","赛事名称");

	/**
	 * 比赛开始时间 | datetime
	 */
	public final DateTableField<Date> startTime = new DateTableFieldImpl<Date>(this,"start_time","startTime","比赛开始时间");

	/**
	 * 比赛结束时间 | datetime
	 */
	public final DateTableField<Date> endTime = new DateTableFieldImpl<Date>(this,"end_time","endTime","比赛结束时间");

	/**
	 * 参赛人数上限 | int(11)
	 */
	public final TableField<Integer> limitNum = new TableFieldImpl<Integer>(this,"limit_num","limitNum","参赛人数上限");

	/**
	 * 已参赛人数 | int(11)
	 */
	public final TableField<Integer> num = new TableFieldImpl<Integer>(this,"num","num","已参赛人数");

	/**
	 * 赛事状态(0-未开始,1-进行中,2-结束,3-作废) | tinyint(4)
	 */
	public final TableField<Integer> eventStatus = new TableFieldImpl<Integer>(this,"event_status","eventStatus","赛事状态(0-未开始,1-进行中,2-结束,3-作废)");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {gameEventId,clientReqId,gameUserId,eventName,startTime,endTime,limitNum,num,eventStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGameEventInfo[table=game_event_info]";
	}
}
