package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TGrmHqUserInfo extends AbstractTable {

	static {
		init();
	}

	private TGrmHqUserInfo(){
		super.tableName = "grm_hq_user_info";
	}

	private TGrmHqUserInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmHqUserInfo getInstance() {
		return new TGrmHqUserInfo();
	}

	public static final TGrmHqUserInfo getInstance(String aliasName) {
		return new TGrmHqUserInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("mobile", "phone");
		allFieldMap.put("nameChs", "name_chs");
		allFieldMap.put("nameEng", "name_eng");
		allFieldMap.put("nameCht", "name_cht");
		allFieldMap.put("sex", "sex");
		allFieldMap.put("address", "address");
		allFieldMap.put("telNo", "tel_no");
		allFieldMap.put("nationality", "nationality");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | char(13)
	 */
	public final TableField<String> mobile = new TableFieldImpl<String>(this,"phone","phone","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> nameChs = new TableFieldImpl<String>(this,"name_chs","nameChs","");

	/**
	 *  | varchar(128)
	 */
	public final TableField<String> nameEng = new TableFieldImpl<String>(this,"name_eng","nameEng","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> nameCht = new TableFieldImpl<String>(this,"name_cht","nameCht","");

	/**
	 *  | smallint(6)
	 */
	public final TableField<Integer> sex = new TableFieldImpl<Integer>(this,"sex","sex","");

	/**
	 *  | varchar(256)
	 */
	public final TableField<String> address = new TableFieldImpl<String>(this,"address","address","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> telNo = new TableFieldImpl<String>(this,"tel_no","telNo","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> nationality = new TableFieldImpl<Integer>(this,"nationality","nationality","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,mobile,nameChs,nameEng,nameCht,sex,address,telNo,nationality};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmHqUserInfo[table=grm_hq_user_info]";
	}
}
