package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGrmServerGroup extends AbstractTable {

	static {
		init();
	}

	private TGrmServerGroup(){
		super.tableName = "grm_server_group";
	}

	private TGrmServerGroup(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmServerGroup getInstance() {
		return new TGrmServerGroup();
	}

	public static final TGrmServerGroup getInstance(String aliasName) {
		return new TGrmServerGroup(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("serverGroupId", "server_group_id");
		allFieldMap.put("groupCode", "group_code");
		allFieldMap.put("groupName", "group_name");
		allFieldMap.put("createDate", "create_date");
		allFieldMap.put("groupDesc", "group_desc");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"server_group_id","serverGroupId","");
	public final TableField<Integer> serverGroupId = new TableFieldImpl<Integer>(this,"server_group_id","serverGroupId","");

	/**
	 *  | varchar(16)
	 */
	public final TableField<String> groupCode = new TableFieldImpl<String>(this,"group_code","groupCode","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> groupName = new TableFieldImpl<String>(this,"group_name","groupName","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createDate = new DateTableFieldImpl<Date>(this,"create_date","createDate","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> groupDesc = new TableFieldImpl<String>(this,"group_desc","groupDesc","");

	private final TableField<?>[] allFields = new TableField<?>[] {serverGroupId,groupCode,groupName,createDate,groupDesc};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmServerGroup[table=grm_server_group]";
	}
}
