package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGrmTableSyncIndex extends AbstractTable {

	static {
		init();
	}

	private TGrmTableSyncIndex(){
		super.tableName = "grm_table_sync_index";
	}

	private TGrmTableSyncIndex(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmTableSyncIndex getInstance() {
		return new TGrmTableSyncIndex();
	}

	public static final TGrmTableSyncIndex getInstance(String aliasName) {
		return new TGrmTableSyncIndex(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("tableName", "table_name");
		allFieldMap.put("positionStr", "position_str");
		allFieldMap.put("versionNo", "version_no");
		allFieldMap.put("lastSyncTime", "last_sync_time");
		allFieldMap.put("lastSyncRecs", "last_sync_recs");
		allFieldMap.put("positionFieldName", "position_field_name");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> tableName = new TableFieldImpl<String>(this,"table_name","tableName","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> positionStr = new TableFieldImpl<String>(this,"position_str","positionStr","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> versionNo = new TableFieldImpl<Long>(this,"version_no","versionNo","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> lastSyncTime = new DateTableFieldImpl<Date>(this,"last_sync_time","lastSyncTime","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> lastSyncRecs = new TableFieldImpl<Integer>(this,"last_sync_recs","lastSyncRecs","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> positionFieldName = new TableFieldImpl<String>(this,"position_field_name","positionFieldName","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,tableName,positionStr,versionNo,lastSyncTime,lastSyncRecs,positionFieldName};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmTableSyncIndex[table=grm_table_sync_index]";
	}
}
