package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TGrmHqPrivilegeFlag extends AbstractTable {

	static {
		init();
	}

	private TGrmHqPrivilegeFlag(){
		super.tableName = "grm_hq_privilege_flag";
	}

	private TGrmHqPrivilegeFlag(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmHqPrivilegeFlag getInstance() {
		return new TGrmHqPrivilegeFlag();
	}

	public static final TGrmHqPrivilegeFlag getInstance(String aliasName) {
		return new TGrmHqPrivilegeFlag(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("privilegeLabel", "privilege_label");
		allFieldMap.put("privilegeId", "privilege_id");
		allFieldMap.put("privilegeDesc", "privilege_desc");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | varchar(64)
	 */
	public final TableField<String> privilegeLabel = new TableFieldImpl<String>(this,"privilege_label","privilegeLabel","");

	/**
	 * 权限唯一编码 | varchar(64)
	 */
	public final TableField<String> privilegeId = new TableFieldImpl<String>(this,"privilege_id","privilegeId","权限唯一编码");

	/**
	 * 权限描述 | varchar(256)
	 */
	public final TableField<String> privilegeDesc = new TableFieldImpl<String>(this,"privilege_desc","privilegeDesc","权限描述");

	private final TableField<?>[] allFields = new TableField<?>[] {id,privilegeLabel,privilegeId,privilegeDesc};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmHqPrivilegeFlag[table=grm_hq_privilege_flag]";
	}
}
