package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TGrmTrdHisFundJour extends AbstractTable {

	static {
		init();
	}

	private TGrmTrdHisFundJour(){
		super.tableName = "grm_trd_his_fund_jour";
	}

	private TGrmTrdHisFundJour(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmTrdHisFundJour getInstance() {
		return new TGrmTrdHisFundJour();
	}

	public static final TGrmTrdHisFundJour getInstance(String aliasName) {
		return new TGrmTrdHisFundJour(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("jourId", "jour_id");
		allFieldMap.put("initDate", "init_date");
		allFieldMap.put("currDate", "curr_date");
		allFieldMap.put("clientId", "client_id");
		allFieldMap.put("fundAccount", "fund_account");
		allFieldMap.put("moneyType", "money_type");
		allFieldMap.put("businessFlag", "business_flag");
		allFieldMap.put("occurBalance", "occur_balance");
		allFieldMap.put("valueDate", "value_date");
		allFieldMap.put("bankId", "bank_id");
		allFieldMap.put("bankAccount", "bank_account");
		allFieldMap.put("extPositionStr", "ext_position_str");
		allFieldMap.put("extSerialNo", "ext_serial_no");
		allFieldMap.put("remark", "remark");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"jour_id","jourId","");
	public final TableField<Long> jourId = new TableFieldImpl<Long>(this,"jour_id","jourId","");

	/**
	 *  | date
	 */
	public final TableField<Date>  pk1 = new TableFieldImpl<Date>(this,"init_date","initDate","");
	public final DateTableField<Date> initDate = new DateTableFieldImpl<Date>(this,"init_date","initDate","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> currDate = new DateTableFieldImpl<Date>(this,"curr_date","currDate","");

	/**
	 *  | varchar(12)
	 */
	public final TableField<String> clientId = new TableFieldImpl<String>(this,"client_id","clientId","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> fundAccount = new TableFieldImpl<Integer>(this,"fund_account","fundAccount","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> moneyType = new TableFieldImpl<Integer>(this,"money_type","moneyType","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> businessFlag = new TableFieldImpl<Integer>(this,"business_flag","businessFlag","");

	/**
	 *  | double
	 */
	public final TableField<Double> occurBalance = new TableFieldImpl<Double>(this,"occur_balance","occurBalance","");

	/**
	 *  | date
	 */
	public final DateTableField<Date> valueDate = new DateTableFieldImpl<Date>(this,"value_date","valueDate","");

	/**
	 *  | varchar(16)
	 */
	public final TableField<String> bankId = new TableFieldImpl<String>(this,"bank_id","bankId","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> bankAccount = new TableFieldImpl<String>(this,"bank_account","bankAccount","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> extPositionStr = new TableFieldImpl<String>(this,"ext_position_str","extPositionStr","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> extSerialNo = new TableFieldImpl<Integer>(this,"ext_serial_no","extSerialNo","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> remark = new TableFieldImpl<String>(this,"remark","remark","");

	private final TableField<?>[] allFields = new TableField<?>[] {jourId,initDate,currDate,clientId,fundAccount,moneyType,businessFlag,occurBalance,valueDate,bankId,bankAccount,extPositionStr,extSerialNo,remark};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmTrdHisFundJour[table=grm_trd_his_fund_jour]";
	}
}
