package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TGrmHqProdPriv extends AbstractTable {

	static {
		init();
	}

	private TGrmHqProdPriv(){
		super.tableName = "grm_hq_prod_priv";
	}

	private TGrmHqProdPriv(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TGrmHqProdPriv getInstance() {
		return new TGrmHqProdPriv();
	}

	public static final TGrmHqProdPriv getInstance(String aliasName) {
		return new TGrmHqProdPriv(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("privilegeId", "privilege_id");
		allFieldMap.put("productId", "product_id");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> privilegeId = new TableFieldImpl<Integer>(this,"privilege_id","privilegeId","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> productId = new TableFieldImpl<Integer>(this,"product_id","productId","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,privilegeId,productId};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TGrmHqProdPriv[table=grm_hq_prod_priv]";
	}
}
