package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class THkAssetInfo extends AbstractTable {

	static {
		init();
	}

	private THkAssetInfo(){
		super.tableName = "hk_asset_info";
	}

	private THkAssetInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THkAssetInfo getInstance() {
		return new THkAssetInfo();
	}

	public static final THkAssetInfo getInstance(String aliasName) {
		return new THkAssetInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("assetId", "asset_id");
		allFieldMap.put("corpId", "corp_id");
		allFieldMap.put("boardCode", "board_code");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 资产ID | varchar(20)
	 */
	public final TableField<String>  pk = new TableFieldImpl<String>(this,"asset_id","assetId","资产ID");
	public final TableField<String> assetId = new TableFieldImpl<String>(this,"asset_id","assetId","资产ID");

	/**
	 * 公司ID | int(11)
	 */
	public final TableField<Integer> corpId = new TableFieldImpl<Integer>(this,"corp_id","corpId","公司ID");

	/**
	 * 板块代码 | int(11)
	 */
	public final TableField<Integer> boardCode = new TableFieldImpl<Integer>(this,"board_code","boardCode","板块代码");

	private final TableField<?>[] allFields = new TableField<?>[] {assetId,corpId,boardCode};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THkAssetInfo[table=hk_asset_info]";
	}
}
