package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqAccountShareInfo extends AbstractTable {

	static {
		init();
	}

	private THqAccountShareInfo(){
		super.tableName = "hq_account_share_info";
	}

	private THqAccountShareInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqAccountShareInfo getInstance() {
		return new THqAccountShareInfo();
	}

	public static final THqAccountShareInfo getInstance(String aliasName) {
		return new THqAccountShareInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("accountShareId", "account_share_id");
		allFieldMap.put("shareUserId", "share_user_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"account_share_id","accountShareId","");
	public final TableField<Long> accountShareId = new TableFieldImpl<Long>(this,"account_share_id","accountShareId","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> shareUserId = new TableFieldImpl<Long>(this,"share_user_id","shareUserId","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	private final TableField<?>[] allFields = new TableField<?>[] {accountShareId,shareUserId,userId,createTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqAccountShareInfo[table=hq_account_share_info]";
	}
}
