package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqLogInfo extends AbstractTable {

	static {
		init();
	}

	private THqLogInfo(){
		super.tableName = "hq_log_info";
	}

	private THqLogInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqLogInfo getInstance() {
		return new THqLogInfo();
	}

	public static final THqLogInfo getInstance(String aliasName) {
		return new THqLogInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("logId", "log_id");
		allFieldMap.put("relationId", "relation_id");
		allFieldMap.put("userName", "user_name");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("loginFrom", "login_from");
		allFieldMap.put("loginIp", "login_ip");
		allFieldMap.put("loginAdr", "login_adr");
		allFieldMap.put("opDesc", "op_desc");
		allFieldMap.put("opTime", "op_time");
		allFieldMap.put("stockName", "stock_name");
		allFieldMap.put("stockCode", "stock_code");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("exchange", "exchange");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"log_id","logId","");
	public final TableField<Long> logId = new TableFieldImpl<Long>(this,"log_id","logId","");

	/**
	 * 关联ID | bigint(20)
	 */
	public final TableField<Long> relationId = new TableFieldImpl<Long>(this,"relation_id","relationId","关联ID");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> userName = new TableFieldImpl<String>(this,"user_name","userName","");

	/**
	 * 用户ID | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","用户ID");

	/**
	 * 来源平台 | varchar(30)
	 */
	public final TableField<String> loginFrom = new TableFieldImpl<String>(this,"login_from","loginFrom","来源平台");

	/**
	 * 来源ip | varchar(30)
	 */
	public final TableField<String> loginIp = new TableFieldImpl<String>(this,"login_ip","loginIp","来源ip");

	/**
	 * 地区 | varchar(30)
	 */
	public final TableField<String> loginAdr = new TableFieldImpl<String>(this,"login_adr","loginAdr","地区");

	/**
	 * 描述 | varchar(255)
	 */
	public final TableField<String> opDesc = new TableFieldImpl<String>(this,"op_desc","opDesc","描述");

	/**
	 * 记录时间 | datetime
	 */
	public final DateTableField<Date> opTime = new DateTableFieldImpl<Date>(this,"op_time","opTime","记录时间");

	/**
	 * 股票名称 | varchar(60)
	 */
	public final TableField<String> stockName = new TableFieldImpl<String>(this,"stock_name","stockName","股票名称");

	/**
	 * 股票代码 | varchar(20)
	 */
	public final TableField<String> stockCode = new TableFieldImpl<String>(this,"stock_code","stockCode","股票代码");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","");

	/**
	 * 美股交易市场 | varchar(30)
	 */
	public final TableField<String> exchange = new TableFieldImpl<String>(this,"exchange","exchange","美股交易市场");

	private final TableField<?>[] allFields = new TableField<?>[] {logId,relationId,userName,userId,loginFrom,loginIp,loginAdr,opDesc,opTime,stockName,stockCode,packageId,exchange};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqLogInfo[table=hq_log_info]";
	}
}
