package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class THqMarketPackageInfo extends AbstractTable {

	static {
		init();
	}

	private THqMarketPackageInfo(){
		super.tableName = "hq_market_package_info";
	}

	private THqMarketPackageInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqMarketPackageInfo getInstance() {
		return new THqMarketPackageInfo();
	}

	public static final THqMarketPackageInfo getInstance(String aliasName) {
		return new THqMarketPackageInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("marketPackageId", "market_package_id");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("marketId", "market_id");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"market_package_id","marketPackageId","");
	public final TableField<Long> marketPackageId = new TableFieldImpl<Long>(this,"market_package_id","marketPackageId","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> marketId = new TableFieldImpl<Long>(this,"market_id","marketId","");

	private final TableField<?>[] allFields = new TableField<?>[] {marketPackageId,packageId,marketId};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqMarketPackageInfo[table=hq_market_package_info]";
	}
}
