package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqMarketInfo extends AbstractTable {

	static {
		init();
	}

	private THqMarketInfo(){
		super.tableName = "hq_market_info";
	}

	private THqMarketInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqMarketInfo getInstance() {
		return new THqMarketInfo();
	}

	public static final THqMarketInfo getInstance(String aliasName) {
		return new THqMarketInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("marketId", "market_id");
		allFieldMap.put("marketName", "market_name");
		allFieldMap.put("marketVersion", "market_version");
		allFieldMap.put("marketType", "market_type");
		allFieldMap.put("marketCode", "market_code");
		allFieldMap.put("feeWay", "fee_way");
		allFieldMap.put("feeScale", "fee_scale");
		allFieldMap.put("ccyType", "ccy_type");
		allFieldMap.put("usePeriod", "use_period");
		allFieldMap.put("clickNum", "click_num");
		allFieldMap.put("srcType", "src_type");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createUser", "create_user");
		allFieldMap.put("updateUser", "update_user");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"market_id","marketId","");
	public final TableField<Long> marketId = new TableFieldImpl<Long>(this,"market_id","marketId","");

	/**
	 * 行情名称 | varchar(60)
	 */
	public final TableField<String> marketName = new TableFieldImpl<String>(this,"market_name","marketName","行情名称");

	/**
	 * 1-内地版,2-海外版,3-通用版 | char(2)
	 */
	public final TableField<String> marketVersion = new TableFieldImpl<String>(this,"market_version","marketVersion","1-内地版,2-海外版,3-通用版");

	/**
	 * 1-港股行情，2-美股行情 | char(2)
	 */
	public final TableField<String> marketType = new TableFieldImpl<String>(this,"market_type","marketType","1-港股行情，2-美股行情");

	/**
	 * 行情代码 | varchar(60)
	 */
	public final TableField<String> marketCode = new TableFieldImpl<String>(this,"market_code","marketCode","行情代码");

	/**
	 * 1-串流，2-bmp，3-点击， | char(2)
	 */
	public final TableField<String> feeWay = new TableFieldImpl<String>(this,"fee_way","feeWay","1-串流，2-bmp，3-点击，");

	/**
	 * 收费价格 | decimal(12,4)
	 */
	public final TableField<Double> feeScale = new TableFieldImpl<Double>(this,"fee_scale","feeScale","收费价格");

	/**
	 * CNY-人民币，USD-美元，HKD-港币 | char(3)
	 */
	public final TableField<String> ccyType = new TableFieldImpl<String>(this,"ccy_type","ccyType","CNY-人民币，USD-美元，HKD-港币");

	/**
	 * 使用期限 | int(11)
	 */
	public final TableField<Integer> usePeriod = new TableFieldImpl<Integer>(this,"use_period","usePeriod","使用期限");

	/**
	 * 使用点数 | int(11)
	 */
	public final TableField<Integer> clickNum = new TableFieldImpl<Integer>(this,"click_num","clickNum","使用点数");

	/**
	 * 来源类型(APP WEB PC) | varchar(10)
	 */
	public final TableField<String> srcType = new TableFieldImpl<String>(this,"src_type","srcType","来源类型(APP WEB PC)");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> createUser = new TableFieldImpl<Long>(this,"create_user","createUser","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> updateUser = new TableFieldImpl<Long>(this,"update_user","updateUser","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {marketId,marketName,marketVersion,marketType,marketCode,feeWay,feeScale,ccyType,usePeriod,clickNum,srcType,isStatus,createUser,updateUser,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqMarketInfo[table=hq_market_info]";
	}
}
