package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqOrderInfo extends AbstractTable {

	static {
		init();
	}

	private THqOrderInfo(){
		super.tableName = "hq_order_info";
	}

	private THqOrderInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqOrderInfo getInstance() {
		return new THqOrderInfo();
	}

	public static final THqOrderInfo getInstance(String aliasName) {
		return new THqOrderInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("orderId", "order_id");
		allFieldMap.put("orderNum", "order_num");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("orderWay", "order_way");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("orderAmount", "order_amount");
		allFieldMap.put("realAmount", "real_amount");
		allFieldMap.put("remark", "remark");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"order_id","orderId","");
	public final TableField<Long> orderId = new TableFieldImpl<Long>(this,"order_id","orderId","");

	/**
	 * 下单数 | int(11)
	 */
	public final TableField<Integer> orderNum = new TableFieldImpl<Integer>(this,"order_num","orderNum","下单数");

	/**
	 * 套餐ID | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","套餐ID");

	/**
	 * 用户ID | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","用户ID");

	/**
	 * 1，自购 2，赠送 | char(2)
	 */
	public final TableField<String> orderWay = new TableFieldImpl<String>(this,"order_way","orderWay","1，自购 2，赠送");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	/**
	 * 应付金额 | decimal(8,4)
	 */
	public final TableField<Double> orderAmount = new TableFieldImpl<Double>(this,"order_amount","orderAmount","应付金额");

	/**
	 * 实付金额 | decimal(8,4)
	 */
	public final TableField<Double> realAmount = new TableFieldImpl<Double>(this,"real_amount","realAmount","实付金额");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> remark = new TableFieldImpl<String>(this,"remark","remark","");

	private final TableField<?>[] allFields = new TableField<?>[] {orderId,orderNum,packageId,userId,orderWay,createTime,isStatus,orderAmount,realAmount,remark};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqOrderInfo[table=hq_order_info]";
	}
}
