package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqSessionInfo extends AbstractTable {

	static {
		init();
	}

	private THqSessionInfo(){
		super.tableName = "hq_session_info";
	}

	private THqSessionInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqSessionInfo getInstance() {
		return new THqSessionInfo();
	}

	public static final THqSessionInfo getInstance(String aliasName) {
		return new THqSessionInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("upTime", "up_time");
		allFieldMap.put("downTime", "down_time");
		allFieldMap.put("isOnline", "is_online");
		allFieldMap.put("loginFrom", "login_from");
		allFieldMap.put("loginIp", "login_ip");
		allFieldMap.put("msg", "remark");
		allFieldMap.put("sessionCode", "session_code");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> upTime = new DateTableFieldImpl<Date>(this,"up_time","upTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> downTime = new DateTableFieldImpl<Date>(this,"down_time","downTime","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isOnline = new TableFieldImpl<Boolean>(this,"is_online","isOnline","");

	/**
	 *  | varchar(30)
	 */
	public final TableField<String> loginFrom = new TableFieldImpl<String>(this,"login_from","loginFrom","");

	/**
	 *  | varchar(30)
	 */
	public final TableField<String> loginIp = new TableFieldImpl<String>(this,"login_ip","loginIp","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> msg = new TableFieldImpl<String>(this,"remark","remark","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> sessionCode = new TableFieldImpl<String>(this,"session_code","token","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,userId,upTime,downTime,isOnline,loginFrom,loginIp,msg,sessionCode};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqSessionInfo[table=hq_session_info]";
	}
}
