package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqUserBasicInfo extends AbstractTable {

	static {
		init();
	}

	private THqUserBasicInfo(){
		super.tableName = "hq_user_basic_info";
	}

	private THqUserBasicInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqUserBasicInfo getInstance() {
		return new THqUserBasicInfo();
	}

	public static final THqUserBasicInfo getInstance(String aliasName) {
		return new THqUserBasicInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userBasicId", "user_basic_id");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"user_basic_id","userBasicId","");
	public final TableField<Long> userBasicId = new TableFieldImpl<Long>(this,"user_basic_id","userBasicId","");

	/**
	 * 行情ID | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","行情ID");

	/**
	 * 用户ID | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","用户ID");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	private final TableField<?>[] allFields = new TableField<?>[] {userBasicId,packageId,userId,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqUserBasicInfo[table=hq_user_basic_info]";
	}
}
