package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqUserStreamInfo extends AbstractTable {

	static {
		init();
	}

	private THqUserStreamInfo(){
		super.tableName = "hq_user_stream_info";
	}

	private THqUserStreamInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqUserStreamInfo getInstance() {
		return new THqUserStreamInfo();
	}

	public static final THqUserStreamInfo getInstance(String aliasName) {
		return new THqUserStreamInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userStreamId", "user_stream_id");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("startTime", "start_time");
		allFieldMap.put("endTime", "end_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("isExpire", "is_expire");
		allFieldMap.put("isShare", "is_share");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"user_stream_id","userStreamId","");
	public final TableField<Long> userStreamId = new TableFieldImpl<Long>(this,"user_stream_id","userStreamId","");

	/**
	 * 行情ID | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","行情ID");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","");

	/**
	 * 服务开始时间 | datetime
	 */
	public final DateTableField<Date> startTime = new DateTableFieldImpl<Date>(this,"start_time","startTime","服务开始时间");

	/**
	 * 服务结束时间 | datetime
	 */
	public final DateTableField<Date> endTime = new DateTableFieldImpl<Date>(this,"end_time","endTime","服务结束时间");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	/**
	 * 0过期,1正常 | tinyint(1)
	 */
	public final TableField<Boolean> isExpire = new TableFieldImpl<Boolean>(this,"is_expire","isExpire","0过期,1正常");

	/**
	 * 0-个人，1-共享 | tinyint(1)
	 */
	public final TableField<Boolean> isShare = new TableFieldImpl<Boolean>(this,"is_share","isShare","0-个人，1-共享");

	private final TableField<?>[] allFields = new TableField<?>[] {userStreamId,packageId,userId,startTime,endTime,createTime,updateTime,isStatus,isExpire,isShare};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqUserStreamInfo[table=hq_user_stream_info]";
	}
}
