package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class THqUserClickInfo extends AbstractTable {

	static {
		init();
	}

	private THqUserClickInfo(){
		super.tableName = "hq_user_click_info";
	}

	private THqUserClickInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final THqUserClickInfo getInstance() {
		return new THqUserClickInfo();
	}

	public static final THqUserClickInfo getInstance(String aliasName) {
		return new THqUserClickInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userClickId", "user_click_id");
		allFieldMap.put("packageId", "package_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("clickTotalNum", "click_total_num");
		allFieldMap.put("clickRestNum", "click_rest_num");
		allFieldMap.put("clickUseNum", "click_use_num");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"user_click_id","userClickId","");
	public final TableField<Long> userClickId = new TableFieldImpl<Long>(this,"user_click_id","userClickId","");

	/**
	 * 行情ID | bigint(20)
	 */
	public final TableField<Long> packageId = new TableFieldImpl<Long>(this,"package_id","packageId","行情ID");

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long> userId = new TableFieldImpl<Long>(this,"user_id","userId","");

	/**
	 * 总点击数 | int(11)
	 */
	public final TableField<Integer> clickTotalNum = new TableFieldImpl<Integer>(this,"click_total_num","clickTotalNum","总点击数");

	/**
	 * 剩余点击数 | int(11)
	 */
	public final TableField<Integer> clickRestNum = new TableFieldImpl<Integer>(this,"click_rest_num","clickRestNum","剩余点击数");

	/**
	 * 已使用点数 | int(11)
	 */
	public final TableField<Integer> clickUseNum = new TableFieldImpl<Integer>(this,"click_use_num","clickUseNum","已使用点数");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	/**
	 * 0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","0-无效，1-有效");

	private final TableField<?>[] allFields = new TableField<?>[] {userClickId,packageId,userId,clickTotalNum,clickRestNum,clickUseNum,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "THqUserClickInfo[table=hq_user_click_info]";
	}
}
