package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TOpenUserDev extends AbstractTable {

	static {
		init();
	}

	private TOpenUserDev(){
		super.tableName = "open_user_dev";
	}

	private TOpenUserDev(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TOpenUserDev getInstance() {
		return new TOpenUserDev();
	}

	public static final TOpenUserDev getInstance(String aliasName) {
		return new TOpenUserDev(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("idcard", "idcard");
		allFieldMap.put("rname", "rname");
		allFieldMap.put("bankcard", "bankcard");
		allFieldMap.put("bankcode", "bankcode");
		allFieldMap.put("riskStartTime", "risk_start_time");
		allFieldMap.put("riskEndTime", "risk_end_time");
		allFieldMap.put("phoneInfo", "phone_info");
		allFieldMap.put("UIP", "UIP");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 自增主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","自增主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","自增主键");

	/**
	 * 用户id | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * 时间戳 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","时间戳");

	/**
	 * 身份证 | varchar(18)
	 */
	public final TableField<String> idcard = new TableFieldImpl<String>(this,"idcard","idcard","身份证");

	/**
	 * 实名 | varchar(20)
	 */
	public final TableField<String> rname = new TableFieldImpl<String>(this,"rname","rname","实名");

	/**
	 * 银行卡 | varchar(50)
	 */
	public final TableField<String> bankcard = new TableFieldImpl<String>(this,"bankcard","bankcard","银行卡");

	/**
	 * 银行代码 | varchar(50)
	 */
	public final TableField<String> bankcode = new TableFieldImpl<String>(this,"bankcode","bankcode","银行代码");

	/**
	 * 风批开始时间 | datetime
	 */
	public final DateTableField<Date> riskStartTime = new DateTableFieldImpl<Date>(this,"risk_start_time","riskStartTime","风批开始时间");

	/**
	 * 风批结束时间 | datetime
	 */
	public final DateTableField<Date> riskEndTime = new DateTableFieldImpl<Date>(this,"risk_end_time","riskEndTime","风批结束时间");

	/**
	 * 手机信息 | varchar(500)
	 */
	public final TableField<String> phoneInfo = new TableFieldImpl<String>(this,"phone_info","phoneInfo","手机信息");

	/**
	 *  | varchar(15)
	 */
	public final TableField<String> UIP = new TableFieldImpl<String>(this,"UIP","UIP","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,userId,createTime,idcard,rname,bankcard,bankcode,riskStartTime,riskEndTime,phoneInfo,UIP};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TOpenUserDev[table=open_user_dev]";
	}
}
