package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPayXfCardBound extends AbstractTable {

	static {
		init();
	}

	private TPayXfCardBound(){
		super.tableName = "pay_xf_card_bound";
	}

	private TPayXfCardBound(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPayXfCardBound getInstance() {
		return new TPayXfCardBound();
	}

	public static final TPayXfCardBound getInstance(String aliasName) {
		return new TPayXfCardBound(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("cardBoundId", "card_bound_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("bindSeq", "bind_seq");
		allFieldMap.put("cardNo", "card_no");
		allFieldMap.put("bankId", "bank_id");
		allFieldMap.put("bankName", "bank_name");
		allFieldMap.put("unbindTime", "unbind_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 银行卡绑定ID,主键，自增长 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"card_bound_id","cardBoundId","银行卡绑定ID,主键，自增长");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","银行卡绑定ID,主键，自增长");

	public final TableField<Integer> cardBoundId = new TableFieldImpl<Integer>(this,"card_bound_id","cardBoundId","银行卡绑定ID,主键，自增长");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 绑定序号,0表示当前绑定其余数字为历史绑定卡号 | int(11)
	 */
	public final TableField<Integer> bindSeq = new TableFieldImpl<Integer>(this,"bind_seq","bindSeq","绑定序号,0表示当前绑定其余数字为历史绑定卡号");

	/**
	 * 卡号 | varchar(25)
	 */
	public final TableField<String> cardNo = new TableFieldImpl<String>(this,"card_no","cardNo","卡号");

	/**
	 * 银行编码,如ICBC | varchar(10)
	 */
	public final TableField<String> bankId = new TableFieldImpl<String>(this,"bank_id","bankId","银行编码,如ICBC");

	/**
	 * 银行名称 | varchar(64)
	 */
	public final TableField<String> bankName = new TableFieldImpl<String>(this,"bank_name","bankName","银行名称");

	/**
	 * 解绑时间 | datetime
	 */
	public final DateTableField<Date> unbindTime = new DateTableFieldImpl<Date>(this,"unbind_time","unbindTime","解绑时间");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {cardBoundId,userId,bindSeq,cardNo,bankId,bankName,unbindTime,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TPayXfCardBound[table=pay_xf_card_bound]";
	}
}
