package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPayWxAcc extends AbstractTable {

	static {
		init();
	}

	private TPayWxAcc(){
		super.tableName = "pay_wx_acc";
	}

	private TPayWxAcc(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPayWxAcc getInstance() {
		return new TPayWxAcc();
	}

	public static final TPayWxAcc getInstance(String aliasName) {
		return new TPayWxAcc(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("wxMatchId", "wx_match_id");
		allFieldMap.put("accountId", "account_id");
		allFieldMap.put("appid", "appid");
		allFieldMap.put("openid", "openid");
		allFieldMap.put("unionid", "unionid");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 对应ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"wx_match_id","wxMatchId","对应ID");
	public final TableField<Integer> wxMatchId = new TableFieldImpl<Integer>(this,"wx_match_id","wxMatchId","对应ID");

	/**
	 * 账户表ID | int(11)
	 */
	public final TableField<Integer> accountId = new TableFieldImpl<Integer>(this,"account_id","accountId","账户表ID");

	/**
	 * 公众账号ID | varchar(32)
	 */
	public final TableField<String> appid = new TableFieldImpl<String>(this,"appid","appid","公众账号ID");

	/**
	 * 微信OpenId | varchar(128)
	 */
	public final TableField<String> openid = new TableFieldImpl<String>(this,"openid","openid","微信OpenId");

	/**
	 * 微信UnionId | varchar(128)
	 */
	public final TableField<String> unionid = new TableFieldImpl<String>(this,"unionid","unionid","微信UnionId");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {wxMatchId,accountId,appid,openid,unionid,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TPayWxAcc[table=pay_wx_acc]";
	}
}
