package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPlatRobotLog extends AbstractTable {

	static {
		init();
	}

	private TPlatRobotLog(){
		super.tableName = "plat_robot_log";
	}

	private TPlatRobotLog(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPlatRobotLog getInstance() {
		return new TPlatRobotLog();
	}

	public static final TPlatRobotLog getInstance(String aliasName) {
		return new TPlatRobotLog(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("msgid", "msgid");
		allFieldMap.put("ask", "ask");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("userName", "user_name");
		allFieldMap.put("type", "type");
		allFieldMap.put("createTime", "create_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 消息流水号 | varchar(50)
	 */
	public final TableField<String> msgid = new TableFieldImpl<String>(this,"msgid","msgid","消息流水号");

	/**
	 * 互动内容 | varchar(150)
	 */
	public final TableField<String> ask = new TableFieldImpl<String>(this,"ask","ask","互动内容");

	/**
	 * 用户ID | varchar(20)
	 */
	public final TableField<String> userId = new TableFieldImpl<String>(this,"user_id","userId","用户ID");

	/**
	 * 用户昵称 | varchar(20)
	 */
	public final TableField<String> userName = new TableFieldImpl<String>(this,"user_name","userName","用户昵称");

	/**
	 * 类型 | varchar(10)
	 */
	public final TableField<String> type = new TableFieldImpl<String>(this,"type","type","类型");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	private final TableField<?>[] allFields = new TableField<?>[] {id,msgid,ask,userId,userName,type,createTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TPlatRobotLog[table=plat_robot_log]";
	}
}
