package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPtfIdxChgHis extends AbstractTable {

	static {
		init();
	}

	private TPtfIdxChgHis(){
		super.tableName = "ptf_idx_chg_his";
	}

	private TPtfIdxChgHis(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPtfIdxChgHis getInstance() {
		return new TPtfIdxChgHis();
	}

	public static final TPtfIdxChgHis getInstance(String aliasName) {
		return new TPtfIdxChgHis(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("ptfIdxChgId", "ptf_idx_chg_id");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("ptfIndex", "ptf_index");
		allFieldMap.put("isReal", "is_real");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 组合指数调整id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"ptf_idx_chg_id","ptfIdxChgId","组合指数调整id");
	public final TableField<Integer> ptfIdxChgId = new TableFieldImpl<Integer>(this,"ptf_idx_chg_id","ptfIdxChgId","组合指数调整id");

	/**
	 * 组合id | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合id");

	/**
	 * 组合指数 | decimal(10,4)
	 */
	public final TableField<Double> ptfIndex = new TableFieldImpl<Double>(this,"ptf_index","ptfIndex","组合指数");

	/**
	 * 是否实盘 | tinyint(1)
	 */
	public final TableField<Boolean> isReal = new TableFieldImpl<Boolean>(this,"is_real","isReal","是否实盘");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 记录是否有效。1有效；0无效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效。1有效；0无效");

	private final TableField<?>[] allFields = new TableField<?>[] {ptfIdxChgId,ptfId,ptfIndex,isReal,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TPtfIdxChgHis[table=ptf_idx_chg_his]";
	}
}
