package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPtfFav extends AbstractTable {

	static {
		init();
	}

	private TPtfFav(){
		super.tableName = "ptf_fav";
	}

	private TPtfFav(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPtfFav getInstance() {
		return new TPtfFav();
	}

	public static final TPtfFav getInstance(String aliasName) {
		return new TPtfFav(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("ptfFavId", "ptf_fav_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("displayNo", "display_no");
		allFieldMap.put("owner", "owner");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"ptf_fav_id","ptfFavId","组合ID");
	public final TableField<Integer> ptfFavId = new TableFieldImpl<Integer>(this,"ptf_fav_id","ptfFavId","组合ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 组合id | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合id");

	/**
	 * 自选组合展示序号 | int(11)
	 */
	public final TableField<Integer> displayNo = new TableFieldImpl<Integer>(this,"display_no","displayNo","自选组合展示序号");

	/**
	 * 组合创建者 | tinyint(1)
	 */
	public final TableField<Boolean> owner = new TableFieldImpl<Boolean>(this,"owner","owner","组合创建者");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 记录更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录更新时间");

	/**
	 * 记录是否有效，1有效，0无效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效，1有效，0无效");

	private final TableField<?>[] allFields = new TableField<?>[] {ptfFavId,userId,ptfId,displayNo,owner,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TPtfFav[table=ptf_fav]";
	}
}
