package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TPtfYld extends AbstractTable {

	static {
		init();
	}

	private TPtfYld(){
		super.tableName = "ptf_yld";
	}

	private TPtfYld(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TPtfYld getInstance() {
		return new TPtfYld();
	}

	public static final TPtfYld getInstance(String aliasName) {
		return new TPtfYld(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("ptfIndex", "ptf_index");
		allFieldMap.put("dayYield", "day_yield");
		allFieldMap.put("weekYield", "week_yield");
		allFieldMap.put("monthYield", "month_yield");
		allFieldMap.put("yearYield", "year_yield");
		allFieldMap.put("natureWeekYield", "nature_week_yield");
		allFieldMap.put("natureMonthYield", "nature_month_yield");
		allFieldMap.put("natureYearYield", "nature_year_yield");
		allFieldMap.put("sinceCreateYield", "since_create_yield");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");

	/**
	 * 组合指数 | decimal(10,4)
	 */
	public final TableField<Double> ptfIndex = new TableFieldImpl<Double>(this,"ptf_index","ptfIndex","组合指数");

	/**
	 * 日增长率 | decimal(10,4)
	 */
	public final TableField<Double> dayYield = new TableFieldImpl<Double>(this,"day_yield","dayYield","日增长率");

	/**
	 * 周增长率(七天) | decimal(10,4)
	 */
	public final TableField<Double> weekYield = new TableFieldImpl<Double>(this,"week_yield","weekYield","周增长率(七天)");

	/**
	 * 月增长率(从上个月的同一天至今天) | decimal(10,4)
	 */
	public final TableField<Double> monthYield = new TableFieldImpl<Double>(this,"month_yield","monthYield","月增长率(从上个月的同一天至今天)");

	/**
	 * 年增长率(从上一年的同一天至今天) | decimal(10,4)
	 */
	public final TableField<Double> yearYield = new TableFieldImpl<Double>(this,"year_yield","yearYield","年增长率(从上一年的同一天至今天)");

	/**
	 * 周增长率(上周日至今天) | decimal(10,4)
	 */
	public final TableField<Double> natureWeekYield = new TableFieldImpl<Double>(this,"nature_week_yield","natureWeekYield","周增长率(上周日至今天)");

	/**
	 * 月增长率(上个月最后一天至今天) | decimal(10,4)
	 */
	public final TableField<Double> natureMonthYield = new TableFieldImpl<Double>(this,"nature_month_yield","natureMonthYield","月增长率(上个月最后一天至今天)");

	/**
	 * 年增长率(去年最后一天至今天) | decimal(10,4)
	 */
	public final TableField<Double> natureYearYield = new TableFieldImpl<Double>(this,"nature_year_yield","natureYearYield","年增长率(去年最后一天至今天)");

	/**
	 * 创建以来的增长率 | decimal(10,4)
	 */
	public final TableField<Double> sinceCreateYield = new TableFieldImpl<Double>(this,"since_create_yield","sinceCreateYield","创建以来的增长率");

	/**
	 * 记录状态 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {ptfId,ptfIndex,dayYield,weekYield,monthYield,yearYield,natureWeekYield,natureMonthYield,natureYearYield,sinceCreateYield,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TPtfYld[table=ptf_yld]";
	}
}
