package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TRealPtfBal extends AbstractTable {

	static {
		init();
	}

	private TRealPtfBal(){
		super.tableName = "real_ptf_bal";
	}

	private TRealPtfBal(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRealPtfBal getInstance() {
		return new TRealPtfBal();
	}

	public static final TRealPtfBal getInstance(String aliasName) {
		return new TRealPtfBal(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("realPtfBalId", "real_ptf_bal_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("brkCustid", "brk_custid");
		allFieldMap.put("isFollow", "is_follow");
		allFieldMap.put("isCurrent", "is_current");
		allFieldMap.put("isConfirm", "is_confirm");
		allFieldMap.put("followPct", "follow_pct");
		allFieldMap.put("ptfVersion", "ptf_version");
		allFieldMap.put("firstBuyTime", "first_buy_time");
		allFieldMap.put("balSyncTime", "bal_sync_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 记录ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"real_ptf_bal_id","realPtfBalId","记录ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","记录ID");

	public final TableField<Integer> realPtfBalId = new TableFieldImpl<Integer>(this,"real_ptf_bal_id","realPtfBalId","记录ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");

	/**
	 * 券商ID | int(11)
	 */
	public final TableField<Integer> brokerId = new TableFieldImpl<Integer>(this,"broker_id","brokerId","券商ID");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> brkCustid = new TableFieldImpl<String>(this,"brk_custid","brkCustid","");

	/**
	 * 是否跟单组合 | tinyint(1)
	 */
	public final TableField<Boolean> isFollow = new TableFieldImpl<Boolean>(this,"is_follow","isFollow","是否跟单组合");

	/**
	 * 是否当前持仓 | tinyint(1)
	 */
	public final TableField<Boolean> isCurrent = new TableFieldImpl<Boolean>(this,"is_current","isCurrent","是否当前持仓");

	/**
	 * 是否有个股成交过 | tinyint(1)
	 */
	public final TableField<Boolean> isConfirm = new TableFieldImpl<Boolean>(this,"is_confirm","isConfirm","是否有个股成交过");

	/**
	 * 跟单市值比例 | decimal(16,6)
	 */
	public final TableField<Double> followPct = new TableFieldImpl<Double>(this,"follow_pct","followPct","跟单市值比例");

	/**
	 * 组合版本号 | int(11)
	 */
	public final TableField<Integer> ptfVersion = new TableFieldImpl<Integer>(this,"ptf_version","ptfVersion","组合版本号");

	/**
	 * 首次买入时间 | datetime
	 */
	public final DateTableField<Date> firstBuyTime = new DateTableFieldImpl<Date>(this,"first_buy_time","firstBuyTime","首次买入时间");

	/**
	 * 组合持仓同步时间 | datetime
	 */
	public final DateTableField<Date> balSyncTime = new DateTableFieldImpl<Date>(this,"bal_sync_time","balSyncTime","组合持仓同步时间");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {realPtfBalId,userId,ptfId,brokerId,brkCustid,isFollow,isCurrent,isConfirm,followPct,ptfVersion,firstBuyTime,balSyncTime,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TRealPtfBal[table=real_ptf_bal]";
	}
}
