package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TRealFundBalHis extends AbstractTable {

	static {
		init();
	}

	private TRealFundBalHis(){
		super.tableName = "real_fund_bal_his";
	}

	private TRealFundBalHis(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRealFundBalHis getInstance() {
		return new TRealFundBalHis();
	}

	public static final TRealFundBalHis getInstance(String aliasName) {
		return new TRealFundBalHis(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("realFundBalHisId", "real_fund_bal_his_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("brkCustid", "brk_custid");
		allFieldMap.put("depositAcc", "deposit_acc");
		allFieldMap.put("ccyType", "ccy_type");
		allFieldMap.put("effectiveFrom", "effective_from");
		allFieldMap.put("effectiveTo", "effective_to");
		allFieldMap.put("totalBal", "total_bal");
		allFieldMap.put("avaBal", "ava_bal");
		allFieldMap.put("cashBal", "cash_bal");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 资金账户ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"real_fund_bal_his_id","realFundBalHisId","资金账户ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","资金账户ID");

	public final TableField<Integer> realFundBalHisId = new TableFieldImpl<Integer>(this,"real_fund_bal_his_id","realFundBalHisId","资金账户ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 券商ID | int(11)
	 */
	public final TableField<Integer> brokerId = new TableFieldImpl<Integer>(this,"broker_id","brokerId","券商ID");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> brkCustid = new TableFieldImpl<String>(this,"brk_custid","brkCustid","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> depositAcc = new TableFieldImpl<String>(this,"deposit_acc","depositAcc","");

	/**
	 * 币种 | char(3)
	 */
	public final TableField<String> ccyType = new TableFieldImpl<String>(this,"ccy_type","ccyType","币种");

	/**
	 * 有效起始时间 | datetime
	 */
	public final DateTableField<Date> effectiveFrom = new DateTableFieldImpl<Date>(this,"effective_from","effectiveFrom","有效起始时间");

	/**
	 * 有效截止时间 | datetime
	 */
	public final DateTableField<Date> effectiveTo = new DateTableFieldImpl<Date>(this,"effective_to","effectiveTo","有效截止时间");

	/**
	 * 资金总额 | decimal(16,4)
	 */
	public final TableField<Double> totalBal = new TableFieldImpl<Double>(this,"total_bal","totalBal","资金总额");

	/**
	 * 可用资金 | decimal(16,4)
	 */
	public final TableField<Double> avaBal = new TableFieldImpl<Double>(this,"ava_bal","avaBal","可用资金");

	/**
	 * 可取资金 | decimal(16,4)
	 */
	public final TableField<Double> cashBal = new TableFieldImpl<Double>(this,"cash_bal","cashBal","可取资金");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 最后修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","最后修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {realFundBalHisId,userId,brokerId,brkCustid,depositAcc,ccyType,effectiveFrom,effectiveTo,totalBal,avaBal,cashBal,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TRealFundBalHis[table=real_fund_bal_his]";
	}
}
