package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TRealFundBal extends AbstractTable {

	static {
		init();
	}

	private TRealFundBal(){
		super.tableName = "real_fund_bal";
	}

	private TRealFundBal(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRealFundBal getInstance() {
		return new TRealFundBal();
	}

	public static final TRealFundBal getInstance(String aliasName) {
		return new TRealFundBal(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("realFundBalId", "real_fund_bal_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("brkCustid", "brk_custid");
		allFieldMap.put("depositAcc", "deposit_acc");
		allFieldMap.put("ccyType", "ccy_type");
		allFieldMap.put("isDefault", "is_default");
		allFieldMap.put("totalBal", "total_bal");
		allFieldMap.put("avaBal", "ava_bal");
		allFieldMap.put("cashBal", "cash_bal");
		allFieldMap.put("totalMktval", "total_mktval");
		allFieldMap.put("totalAsset", "total_asset");
		allFieldMap.put("syncTime", "sync_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 资金账户ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"real_fund_bal_id","realFundBalId","资金账户ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","资金账户ID");

	public final TableField<Integer> realFundBalId = new TableFieldImpl<Integer>(this,"real_fund_bal_id","realFundBalId","资金账户ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 券商ID | int(11)
	 */
	public final TableField<Integer> brokerId = new TableFieldImpl<Integer>(this,"broker_id","brokerId","券商ID");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> brkCustid = new TableFieldImpl<String>(this,"brk_custid","brkCustid","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> depositAcc = new TableFieldImpl<String>(this,"deposit_acc","depositAcc","");

	/**
	 * 币种 | char(3)
	 */
	public final TableField<String> ccyType = new TableFieldImpl<String>(this,"ccy_type","ccyType","币种");

	/**
	 * 是否主资金账号 | tinyint(1)
	 */
	public final TableField<Boolean> isDefault = new TableFieldImpl<Boolean>(this,"is_default","isDefault","是否主资金账号");

	/**
	 * 资金总额 | decimal(16,4)
	 */
	public final TableField<Double> totalBal = new TableFieldImpl<Double>(this,"total_bal","totalBal","资金总额");

	/**
	 * 可用资金 | decimal(16,4)
	 */
	public final TableField<Double> avaBal = new TableFieldImpl<Double>(this,"ava_bal","avaBal","可用资金");

	/**
	 * 可取资金 | decimal(16,4)
	 */
	public final TableField<Double> cashBal = new TableFieldImpl<Double>(this,"cash_bal","cashBal","可取资金");

	/**
	 * 股票市值 | decimal(16,4)
	 */
	public final TableField<Double> totalMktval = new TableFieldImpl<Double>(this,"total_mktval","totalMktval","股票市值");

	/**
	 * 总资产 | decimal(16,4)
	 */
	public final TableField<Double> totalAsset = new TableFieldImpl<Double>(this,"total_asset","totalAsset","总资产");

	/**
	 * 同步时间 | datetime
	 */
	public final DateTableField<Date> syncTime = new DateTableFieldImpl<Date>(this,"sync_time","syncTime","同步时间");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 最后修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","最后修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {realFundBalId,userId,brokerId,brkCustid,depositAcc,ccyType,isDefault,totalBal,avaBal,cashBal,totalMktval,totalAsset,syncTime,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TRealFundBal[table=real_fund_bal]";
	}
}
