package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TRewardRecord extends AbstractTable {

	static {
		init();
	}

	private TRewardRecord(){
		super.tableName = "reward_record";
	}

	private TRewardRecord(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TRewardRecord getInstance() {
		return new TRewardRecord();
	}

	public static final TRewardRecord getInstance(String aliasName) {
		return new TRewardRecord(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("rrId", "rr_id");
		allFieldMap.put("batchNo", "batch_no");
		allFieldMap.put("batchDesc", "batch_desc");
		allFieldMap.put("rewardAcountNo", "reward_acount_no");
		allFieldMap.put("isUserfulNow", "is_userful_now");
		allFieldMap.put("rewardDesc", "reward_desc");
		allFieldMap.put("sendDesc", "send_desc");
		allFieldMap.put("msgTitle", "msg_title");
		allFieldMap.put("msgContent", "msg_content");
		allFieldMap.put("rewardNo", "reward_no");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("amount", "amount");
		allFieldMap.put("rewardStatus", "reward_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | int(20) unsigned
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"rr_id","rrId","主键");
	public final TableField<Integer> rrId = new TableFieldImpl<Integer>(this,"rr_id","rrId","主键");

	/**
	 * 批次号 | varchar(32)
	 */
	public final TableField<String> batchNo = new TableFieldImpl<String>(this,"batch_no","batchNo","批次号");

	/**
	 * 批次描述 | varchar(128)
	 */
	public final TableField<String> batchDesc = new TableFieldImpl<String>(this,"batch_desc","batchDesc","批次描述");

	/**
	 * 发款账户号 | varchar(128)
	 */
	public final TableField<String> rewardAcountNo = new TableFieldImpl<String>(this,"reward_acount_no","rewardAcountNo","发款账户号");

	/**
	 * 是否马上可用标志：Y表示马上可用，N 表示要等到下个月后结算才能用户 | char(1)
	 */
	public final TableField<String> isUserfulNow = new TableFieldImpl<String>(this,"is_userful_now","isUserfulNow","是否马上可用标志：Y表示马上可用，N 表示要等到下个月后结算才能用户");

	/**
	 * 入账描述 | varchar(128)
	 */
	public final TableField<String> rewardDesc = new TableFieldImpl<String>(this,"reward_desc","rewardDesc","入账描述");

	/**
	 * 发放推送描述 | varchar(128)
	 */
	public final TableField<String> sendDesc = new TableFieldImpl<String>(this,"send_desc","sendDesc","发放推送描述");

	/**
	 * 服务通知标题 | varchar(128)
	 */
	public final TableField<String> msgTitle = new TableFieldImpl<String>(this,"msg_title","msgTitle","服务通知标题");

	/**
	 * 服务通知内容 | varchar(128)
	 */
	public final TableField<String> msgContent = new TableFieldImpl<String>(this,"msg_content","msgContent","服务通知内容");

	/**
	 * 当次发放序号 | int(20)
	 */
	public final TableField<Integer> rewardNo = new TableFieldImpl<Integer>(this,"reward_no","rewardNo","当次发放序号");

	/**
	 * 用户ID | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 *  | decimal(16,2)
	 */
	public final TableField<BigDecimal> amount = new TableFieldImpl<BigDecimal>(this,"amount","amount","");

	/**
	 * 状态标识，0未审核，1审核通过，2作废 | tinyint(4)
	 */
	public final TableField<Integer> rewardStatus = new TableFieldImpl<Integer>(this,"reward_status","rewardStatus","状态标识，0未审核，1审核通过，2作废");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	private final TableField<?>[] allFields = new TableField<?>[] {rrId,batchNo,batchDesc,rewardAcountNo,isUserfulNow,rewardDesc,sendDesc,msgTitle,msgContent,rewardNo,userId,amount,rewardStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TRewardRecord[table=reward_record]";
	}
}
