package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSecItemaccountApply extends AbstractTable {

	static {
		init();
	}

	private TSecItemaccountApply(){
		super.tableName = "sec_itemaccount_apply";
	}

	private TSecItemaccountApply(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSecItemaccountApply getInstance() {
		return new TSecItemaccountApply();
	}

	public static final TSecItemaccountApply getInstance(String aliasName) {
		return new TSecItemaccountApply(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("outsideId", "outside_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("userNameEn", "user_name_en");
		allFieldMap.put("userNameCn", "user_name_cn");
		allFieldMap.put("state", "state");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("subAccountNo", "sub_account_no");
		allFieldMap.put("fundAccount", "fund_account");
		allFieldMap.put("clientId", "client_id");
		allFieldMap.put("isFind", "is_find");
		allFieldMap.put("accountName", "account_name");
		allFieldMap.put("exportState", "export_state");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 申请人账号 | bigint(20)
	 */
	public final TableField<Long> outsideId = new TableFieldImpl<Long>(this,"outside_id","outsideId","申请人账号");

	/**
	 *  | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","");

	/**
	 * 申请人英文名称 | varchar(50)
	 */
	public final TableField<String> userNameEn = new TableFieldImpl<String>(this,"user_name_en","userNameEn","申请人英文名称");

	/**
	 * 申请人中文名称 | varchar(50)
	 */
	public final TableField<String> userNameCn = new TableFieldImpl<String>(this,"user_name_cn","userNameCn","申请人中文名称");

	/**
	 * 申请状态 0申请中1申请成功2失效3审核中 | tinyint(4)
	 */
	public final TableField<Integer> state = new TableFieldImpl<Integer>(this,"state","state","申请状态 0申请中1申请成功2失效3审核中");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 中银子账号 | varchar(20)
	 */
	public final TableField<String> subAccountNo = new TableFieldImpl<String>(this,"sub_account_no","subAccountNo","中银子账号");

	/**
	 * 资金账号 | varchar(20)
	 */
	public final TableField<String> fundAccount = new TableFieldImpl<String>(this,"fund_account","fundAccount","资金账号");

	/**
	 * 交易账号 | varchar(20)
	 */
	public final TableField<String> clientId = new TableFieldImpl<String>(this,"client_id","clientId","交易账号");

	/**
	 * 是否查询全部 | int(2)
	 */
	public final TableField<Integer> isFind = new TableFieldImpl<Integer>(this,"is_find","isFind","是否查询全部");

	/**
	 * 申请人户名 | varchar(50)
	 */
	public final TableField<String> accountName = new TableFieldImpl<String>(this,"account_name","accountName","申请人户名");

	/**
	 * 导出状态 0未导出 1已导出 | tinyint(4)
	 */
	public final TableField<Integer> exportState = new TableFieldImpl<Integer>(this,"export_state","exportState","导出状态 0未导出 1已导出");

	private final TableField<?>[] allFields = new TableField<?>[] {id,outsideId,userId,userNameEn,userNameCn,state,createTime,updateTime,subAccountNo,fundAccount,clientId,isFind,accountName,exportState};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSecItemaccountApply[table=sec_itemaccount_apply]";
	}
}
