package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSimuStkBal extends AbstractTable {

	static {
		init();
	}

	private TSimuStkBal(){
		super.tableName = "simu_stk_bal";
	}

	private TSimuStkBal(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSimuStkBal getInstance() {
		return new TSimuStkBal();
	}

	public static final TSimuStkBal getInstance(String aliasName) {
		return new TSimuStkBal(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("simuStkBalId", "simu_stk_bal_id");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("assetId", "asset_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("isCurrent", "is_current");
		allFieldMap.put("exchangeType", "exchange_type");
		allFieldMap.put("stkCode", "stk_code");
		allFieldMap.put("syncTime", "sync_time");
		allFieldMap.put("totalBal", "total_bal");
		allFieldMap.put("avalBal", "aval_bal");
		allFieldMap.put("simuBuyPrice", "simu_buy_price");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 记录ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"simu_stk_bal_id","simuStkBalId","记录ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","记录ID");

	public final TableField<Integer> simuStkBalId = new TableFieldImpl<Integer>(this,"simu_stk_bal_id","simuStkBalId","记录ID");

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> assetId = new TableFieldImpl<String>(this,"asset_id","assetId","");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 是否当前持仓 | tinyint(1)
	 */
	public final TableField<Boolean> isCurrent = new TableFieldImpl<Boolean>(this,"is_current","isCurrent","是否当前持仓");

	/**
	 *  | varchar(6)
	 */
	public final TableField<String> exchangeType = new TableFieldImpl<String>(this,"exchange_type","exchangeType","");

	/**
	 *  | varchar(12)
	 */
	public final TableField<String> stkCode = new TableFieldImpl<String>(this,"stk_code","stkCode","");

	/**
	 * 同步时间 | datetime
	 */
	public final DateTableField<Date> syncTime = new DateTableFieldImpl<Date>(this,"sync_time","syncTime","同步时间");

	/**
	 * 总余额 | decimal(16,4)
	 */
	public final TableField<Double> totalBal = new TableFieldImpl<Double>(this,"total_bal","totalBal","总余额");

	/**
	 * 可用余额 | decimal(16,4)
	 */
	public final TableField<Double> avalBal = new TableFieldImpl<Double>(this,"aval_bal","avalBal","可用余额");

	/**
	 * 模拟买入成本价 | decimal(10,4)
	 */
	public final TableField<Double> simuBuyPrice = new TableFieldImpl<Double>(this,"simu_buy_price","simuBuyPrice","模拟买入成本价");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {simuStkBalId,ptfId,assetId,userId,isCurrent,exchangeType,stkCode,syncTime,totalBal,avalBal,simuBuyPrice,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TSimuStkBal[table=simu_stk_bal]";
	}
}
