package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSimuPtfBal extends AbstractTable {

	static {
		init();
	}

	private TSimuPtfBal(){
		super.tableName = "simu_ptf_bal";
	}

	private TSimuPtfBal(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSimuPtfBal getInstance() {
		return new TSimuPtfBal();
	}

	public static final TSimuPtfBal getInstance(String aliasName) {
		return new TSimuPtfBal(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("simuPtfBalId", "simu_ptf_bal_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("ptfId", "ptf_id");
		allFieldMap.put("simuAcc", "simu_acc");
		allFieldMap.put("initBal", "init_bal");
		allFieldMap.put("ttlBal", "ttl_bal");
		allFieldMap.put("avlBal", "avl_bal");
		allFieldMap.put("balSyncTime", "bal_sync_time");
		allFieldMap.put("syncInterval", "sync_interval");
		allFieldMap.put("syncBeginTime", "sync_begin_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 记录ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"simu_ptf_bal_id","simuPtfBalId","记录ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","记录ID");

	public final TableField<Integer> simuPtfBalId = new TableFieldImpl<Integer>(this,"simu_ptf_bal_id","simuPtfBalId","记录ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 组合ID | int(11)
	 */
	public final TableField<Integer> ptfId = new TableFieldImpl<Integer>(this,"ptf_id","ptfId","组合ID");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> simuAcc = new TableFieldImpl<String>(this,"simu_acc","simuAcc","");

	/**
	 * 初始金额 | decimal(16,4)
	 */
	public final TableField<Double> initBal = new TableFieldImpl<Double>(this,"init_bal","initBal","初始金额");

	/**
	 * 模拟组合当前资金 | decimal(16,4)
	 */
	public final TableField<Double> ttlBal = new TableFieldImpl<Double>(this,"ttl_bal","ttlBal","模拟组合当前资金");

	/**
	 * 模拟组合可用资金 | decimal(16,4)
	 */
	public final TableField<Double> avlBal = new TableFieldImpl<Double>(this,"avl_bal","avlBal","模拟组合可用资金");

	/**
	 * 组合持仓同步时间 | datetime
	 */
	public final DateTableField<Date> balSyncTime = new DateTableFieldImpl<Date>(this,"bal_sync_time","balSyncTime","组合持仓同步时间");

	/**
	 * 上次同步间隔 | int(11)
	 */
	public final TableField<Integer> syncInterval = new TableFieldImpl<Integer>(this,"sync_interval","syncInterval","上次同步间隔");

	/**
	 * 下次同步开始时间 | datetime
	 */
	public final DateTableField<Date> syncBeginTime = new DateTableFieldImpl<Date>(this,"sync_begin_time","syncBeginTime","下次同步开始时间");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {simuPtfBalId,userId,ptfId,simuAcc,initBal,ttlBal,avlBal,balSyncTime,syncInterval,syncBeginTime,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TSimuPtfBal[table=simu_ptf_bal]";
	}
}
