package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSmsTemplate extends AbstractTable {

	static {
		init();
	}

	private TSmsTemplate(){
		super.tableName = "sms_template";
	}

	private TSmsTemplate(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSmsTemplate getInstance() {
		return new TSmsTemplate();
	}

	public static final TSmsTemplate getInstance(String aliasName) {
		return new TSmsTemplate(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("templateId", "template_id");
		allFieldMap.put("code", "code");
		allFieldMap.put("event", "event");
		allFieldMap.put("busType", "bus_type");
		allFieldMap.put("channel", "channel");
		allFieldMap.put("createOpr", "create_opr");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateOpr", "update_opr");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 消息模板id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"template_id","templateId","消息模板id");
	public final TableField<Integer> templateId = new TableFieldImpl<Integer>(this,"template_id","templateId","消息模板id");

	/**
	 * 消息代码 | int(4)
	 */
	public final TableField<Integer> code = new TableFieldImpl<Integer>(this,"code","code","消息代码");

	/**
	 *  | varchar(2000)
	 */
	public final TableField<String> event = new TableFieldImpl<String>(this,"event","event","");

	/**
	 * 业务类型 | tinyint(4)
	 */
	public final TableField<Integer> busType = new TableFieldImpl<Integer>(this,"bus_type","busType","业务类型");

	/**
	 *  | varchar(2)
	 */
	public final TableField<String> channel = new TableFieldImpl<String>(this,"channel","channel","");

	/**
	 * 创建人 | int(11)
	 */
	public final TableField<Integer> createOpr = new TableFieldImpl<Integer>(this,"create_opr","createOpr","创建人");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改人 | int(11)
	 */
	public final TableField<Integer> updateOpr = new TableFieldImpl<Integer>(this,"update_opr","updateOpr","修改人");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 记录是否有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效");

	private final TableField<?>[] allFields = new TableField<?>[] {templateId,code,event,busType,channel,createOpr,createTime,updateOpr,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSmsTemplate[table=sms_template]";
	}
}
