package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSmsUpstream extends AbstractTable {

	static {
		init();
	}

	private TSmsUpstream(){
		super.tableName = "sms_upstream";
	}

	private TSmsUpstream(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSmsUpstream getInstance() {
		return new TSmsUpstream();
	}

	public static final TSmsUpstream getInstance(String aliasName) {
		return new TSmsUpstream(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("upstreamId", "upstream_id");
		allFieldMap.put("channel", "channel");
		allFieldMap.put("mobile", "phone");
		allFieldMap.put("content", "content");
		allFieldMap.put("sendTime", "send_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 短信上行接收 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"upstream_id","upstreamId","短信上行接收");
	public final TableField<Integer> upstreamId = new TableFieldImpl<Integer>(this,"upstream_id","upstreamId","短信上行接收");

	/**
	 * 短信通道 | varchar(100)
	 */
	public final TableField<String> channel = new TableFieldImpl<String>(this,"channel","channel","短信通道");

	/**
	 * 手机号码 | char(15)
	 */
	public final TableField<String> mobile = new TableFieldImpl<String>(this,"phone","phone","手机号码");

	/**
	 * 上行短信的内容 | varchar(200)
	 */
	public final TableField<String> content = new TableFieldImpl<String>(this,"content","content","上行短信的内容");

	/**
	 * 上行短信的发送的时间 | datetime
	 */
	public final DateTableField<Date> sendTime = new DateTableFieldImpl<Date>(this,"send_time","sendTime","上行短信的发送的时间");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 记录更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录更新时间");

	private final TableField<?>[] allFields = new TableField<?>[] {upstreamId,channel,mobile,content,sendTime,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSmsUpstream[table=sms_upstream]";
	}
}
