package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSmsPush extends AbstractTable {

	static {
		init();
	}

	private TSmsPush(){
		super.tableName = "sms_push";
	}

	private TSmsPush(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSmsPush getInstance() {
		return new TSmsPush();
	}

	public static final TSmsPush getInstance(String aliasName) {
		return new TSmsPush(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("smsPushId", "sms_push_id");
		allFieldMap.put("clientid", "clientid");
		allFieldMap.put("pushType", "push_type");
		allFieldMap.put("title", "title");
		allFieldMap.put("content", "content");
		allFieldMap.put("osType", "os_type");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 推送id，主键，发送一条记录一条 | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"sms_push_id","smsPushId","推送id，主键，发送一条记录一条");
	public final TableField<Integer> smsPushId = new TableFieldImpl<Integer>(this,"sms_push_id","smsPushId","推送id，主键，发送一条记录一条");

	/**
	 *  | varchar(5000)
	 */
	public final TableField<String> clientid = new TableFieldImpl<String>(this,"clientid","clientid","");

	/**
	 * 推送类型:0打开应用；1打开通知；2点击下载（暂不用）；3透传信息 | tinyint(4)
	 */
	public final TableField<Integer> pushType = new TableFieldImpl<Integer>(this,"push_type","pushType","推送类型:0打开应用；1打开通知；2点击下载（暂不用）；3透传信息");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> title = new TableFieldImpl<String>(this,"title","title","");

	/**
	 *  | varchar(2500)
	 */
	public final TableField<String> content = new TableFieldImpl<String>(this,"content","content","");

	/**
	 * 设备类型 | tinyint(4)
	 */
	public final TableField<Integer> osType = new TableFieldImpl<Integer>(this,"os_type","osType","设备类型");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 记录是否有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效");

	private final TableField<?>[] allFields = new TableField<?>[] {smsPushId,clientid,pushType,title,content,osType,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSmsPush[table=sms_push]";
	}
}
