package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSmsSend extends AbstractTable {

	static {
		init();
	}

	private TSmsSend(){
		super.tableName = "sms_send";
	}

	private TSmsSend(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSmsSend getInstance() {
		return new TSmsSend();
	}

	public static final TSmsSend getInstance(String aliasName) {
		return new TSmsSend(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("smsSendId", "sms_send_id");
		allFieldMap.put("appCode", "app_code");
		allFieldMap.put("templateCode", "template_code");
		allFieldMap.put("extension", "extension");
		allFieldMap.put("phoneNumber", "phone_number");
		allFieldMap.put("message", "message");
		allFieldMap.put("channel", "channel");
		allFieldMap.put("sendStatus", "send_status");
		allFieldMap.put("rtnMsg", "rtn_msg");
		allFieldMap.put("failureResend", "failure_resend");
		allFieldMap.put("failureNum", "failure_num");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 短信发送id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"sms_send_id","smsSendId","短信发送id");
	public final TableField<Integer> smsSendId = new TableFieldImpl<Integer>(this,"sms_send_id","smsSendId","短信发送id");

	/**
	 * app编码 | varchar(10)
	 */
	public final TableField<String> appCode = new TableFieldImpl<String>(this,"app_code","appCode","app编码");

	/**
	 * 模板编码 | varchar(50)
	 */
	public final TableField<String> templateCode = new TableFieldImpl<String>(this,"template_code","templateCode","模板编码");

	/**
	 * 业务扩展码，用于区分各种业务 | char(4)
	 */
	public final TableField<String> extension = new TableFieldImpl<String>(this,"extension","extension","业务扩展码，用于区分各种业务");

	/**
	 *  | varchar(5000)
	 */
	public final TableField<String> phoneNumber = new TableFieldImpl<String>(this,"phone_number","phoneNumber","");

	/**
	 *  | varchar(1000)
	 */
	public final TableField<String> message = new TableFieldImpl<String>(this,"message","message","");

	/**
	 *  | varchar(5)
	 */
	public final TableField<String> channel = new TableFieldImpl<String>(this,"channel","channel","");

	/**
	 * 发送状态 | tinyint(4)
	 */
	public final TableField<Integer> sendStatus = new TableFieldImpl<Integer>(this,"send_status","sendStatus","发送状态");

	/**
	 *  | varchar(2000)
	 */
	public final TableField<String> rtnMsg = new TableFieldImpl<String>(this,"rtn_msg","rtnMsg","");

	/**
	 * 失败是否重发。1重发；0不重发 | tinyint(1)
	 */
	public final TableField<Boolean> failureResend = new TableFieldImpl<Boolean>(this,"failure_resend","failureResend","失败是否重发。1重发；0不重发");

	/**
	 * 失败次数。目前约定失败3次不再重发 | tinyint(4)
	 */
	public final TableField<Integer> failureNum = new TableFieldImpl<Integer>(this,"failure_num","failureNum","失败次数。目前约定失败3次不再重发");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 记录是否有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效");

	private final TableField<?>[] allFields = new TableField<?>[] {smsSendId,appCode,templateCode,extension,phoneNumber,message,channel,sendStatus,rtnMsg,failureResend,failureNum,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSmsSend[table=sms_send]";
	}
}
