package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSnTask extends AbstractTable {

	static {
		init();
	}

	private TSnTask(){
		super.tableName = "sn_task";
	}

	private TSnTask(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSnTask getInstance() {
		return new TSnTask();
	}

	public static final TSnTask getInstance(String aliasName) {
		return new TSnTask(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("snTaskId", "sn_task_id");
		allFieldMap.put("taskType", "task_type");
		allFieldMap.put("taskName", "task_name");
		allFieldMap.put("taskTypeDesc", "task_type_desc");
		allFieldMap.put("featId", "feat_id");
		allFieldMap.put("eventCode", "event_code");
		allFieldMap.put("calType", "cal_type");
		allFieldMap.put("targetNum", "target_num");
		allFieldMap.put("experience", "experience");
		allFieldMap.put("coin", "coin");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("creator", "creator");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("modifier", "modifier");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"sn_task_id","snTaskId","");
	public final TableField<Integer> snTaskId = new TableFieldImpl<Integer>(this,"sn_task_id","snTaskId","");

	/**
	 * 任务的任务类型（任务类型可以理解为任务编码，即对应具体的任务） | varchar(45)
	 */
	public final TableField<String> taskType = new TableFieldImpl<String>(this,"task_type","taskType","任务的任务类型（任务类型可以理解为任务编码，即对应具体的任务）");

	/**
	 * 任务名称 | varchar(128)
	 */
	public final TableField<String> taskName = new TableFieldImpl<String>(this,"task_name","taskName","任务名称");

	/**
	 * 任务类型描述 | varchar(128)
	 */
	public final TableField<String> taskTypeDesc = new TableFieldImpl<String>(this,"task_type_desc","taskTypeDesc","任务类型描述");

	/**
	 * 功勋id | int(11)
	 */
	public final TableField<Integer> featId = new TableFieldImpl<Integer>(this,"feat_id","featId","功勋id");

	/**
	 * 任务所属的事件类型 | varchar(45)
	 */
	public final TableField<String> eventCode = new TableFieldImpl<String>(this,"event_code","eventCode","任务所属的事件类型");

	/**
	 * 任务的计算类型 | varchar(45)
	 */
	public final TableField<String> calType = new TableFieldImpl<String>(this,"cal_type","calType","任务的计算类型");

	/**
	 * 目标数字 | int(11)
	 */
	public final TableField<Integer> targetNum = new TableFieldImpl<Integer>(this,"target_num","targetNum","目标数字");

	/**
	 * 任务完成可以领取的经验值（功勋值） | int(11)
	 */
	public final TableField<Integer> experience = new TableFieldImpl<Integer>(this,"experience","experience","任务完成可以领取的经验值（功勋值）");

	/**
	 * 任务完成可以领取的金币值 | int(11)
	 */
	public final TableField<Integer> coin = new TableFieldImpl<Integer>(this,"coin","coin","任务完成可以领取的金币值");

	/**
	 * 是否有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","是否有效");

	/**
	 * 创建者 | varchar(45)
	 */
	public final TableField<String> creator = new TableFieldImpl<String>(this,"creator","creator","创建者");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改者 | varchar(45)
	 */
	public final TableField<String> modifier = new TableFieldImpl<String>(this,"modifier","modifier","修改者");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {snTaskId,taskType,taskName,taskTypeDesc,featId,eventCode,calType,targetNum,experience,coin,isStatus,creator,createTime,modifier,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSnTask[table=sn_task]";
	}
}
