package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TStatChannel extends AbstractTable {

	static {
		init();
	}

	private TStatChannel(){
		super.tableName = "stat_channel";
	}

	private TStatChannel(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TStatChannel getInstance() {
		return new TStatChannel();
	}

	public static final TStatChannel getInstance(String aliasName) {
		return new TStatChannel(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("activityId", "activity_id");
		allFieldMap.put("sourceId", "source_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("type", "type");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("operateTime", "operate_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 活动ID | int(5)
	 */
	public final TableField<Integer> activityId = new TableFieldImpl<Integer>(this,"activity_id","activityId","活动ID");

	/**
	 * 来源ID | int(5)
	 */
	public final TableField<Integer> sourceId = new TableFieldImpl<Integer>(this,"source_id","sourceId","来源ID");

	/**
	 * 用户ID | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 类型编号 1:注册 2：开户 3：入金 | int(5)
	 */
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","类型编号 1:注册 2：开户 3：入金");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 操作时间 | datetime
	 */
	public final DateTableField<Date> operateTime = new DateTableFieldImpl<Date>(this,"operate_time","operateTime","操作时间");

	private final TableField<?>[] allFields = new TableField<?>[] {id,activityId,sourceId,userId,type,createTime,operateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TStatChannel[table=stat_channel]";
	}
}
