package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TStkHisCfm extends AbstractTable {

	static {
		init();
	}

	private TStkHisCfm(){
		super.tableName = "stk_his_cfm";
	}

	private TStkHisCfm(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TStkHisCfm getInstance() {
		return new TStkHisCfm();
	}

	public static final TStkHisCfm getInstance(String aliasName) {
		return new TStkHisCfm(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("matchcode", "matchcode");
		allFieldMap.put("ordersno", "ordersno");
		allFieldMap.put("stkcode", "stkcode");
		allFieldMap.put("stkname", "stkname");
		allFieldMap.put("bsflag", "bsflag");
		allFieldMap.put("matchtype", "matchtype");
		allFieldMap.put("matchprice", "matchprice");
		allFieldMap.put("matchamt", "matchamt");
		allFieldMap.put("secuid", "secuid");
		allFieldMap.put("market", "market");
		allFieldMap.put("inputid", "inputid");
		allFieldMap.put("matchdate", "matchdate");
		allFieldMap.put("feeYhs", "fee_yhs");
		allFieldMap.put("feeGhf", "fee_ghf");
		allFieldMap.put("feeQsf", "fee_qsf");
		allFieldMap.put("orderid", "orderid");
		allFieldMap.put("poststr", "poststr");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(255)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"matchcode","matchcode","");
	public final TableField<Integer> matchcode = new TableFieldImpl<Integer>(this,"matchcode","matchcode","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> ordersno = new TableFieldImpl<Integer>(this,"ordersno","ordersno","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> stkcode = new TableFieldImpl<String>(this,"stkcode","stkcode","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> stkname = new TableFieldImpl<String>(this,"stkname","stkname","");

	/**
	 *  | varchar(2)
	 */
	public final TableField<String> bsflag = new TableFieldImpl<String>(this,"bsflag","bsflag","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> matchtype = new TableFieldImpl<String>(this,"matchtype","matchtype","");

	/**
	 *  | decimal(10,4)
	 */
	public final TableField<Double> matchprice = new TableFieldImpl<Double>(this,"matchprice","matchprice","");

	/**
	 *  | decimal(16,4)
	 */
	public final TableField<Double> matchamt = new TableFieldImpl<Double>(this,"matchamt","matchamt","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> secuid = new TableFieldImpl<String>(this,"secuid","secuid","");

	/**
	 *  | varchar(1)
	 */
	public final TableField<String> market = new TableFieldImpl<String>(this,"market","market","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> inputid = new TableFieldImpl<String>(this,"inputid","inputid","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> matchdate = new DateTableFieldImpl<Date>(this,"matchdate","matchdate","");

	/**
	 *  | decimal(10,4)
	 */
	public final TableField<Double> feeYhs = new TableFieldImpl<Double>(this,"fee_yhs","feeYhs","");

	/**
	 *  | decimal(10,4)
	 */
	public final TableField<Double> feeGhf = new TableFieldImpl<Double>(this,"fee_ghf","feeGhf","");

	/**
	 *  | decimal(10,4)
	 */
	public final TableField<Double> feeQsf = new TableFieldImpl<Double>(this,"fee_qsf","feeQsf","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> orderid = new TableFieldImpl<Integer>(this,"orderid","orderid","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> poststr = new TableFieldImpl<String>(this,"poststr","poststr","");

	private final TableField<?>[] allFields = new TableField<?>[] {matchcode,ordersno,stkcode,stkname,bsflag,matchtype,matchprice,matchamt,secuid,market,inputid,matchdate,feeYhs,feeGhf,feeQsf,orderid,poststr};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TStkHisCfm[table=stk_his_cfm]";
	}
}
