package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TStkTodayCfm extends AbstractTable {

	static {
		init();
	}

	private TStkTodayCfm(){
		super.tableName = "stk_today_cfm";
	}

	private TStkTodayCfm(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TStkTodayCfm getInstance() {
		return new TStkTodayCfm();
	}

	public static final TStkTodayCfm getInstance(String aliasName) {
		return new TStkTodayCfm(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("matchcode", "matchcode");
		allFieldMap.put("ordersno", "ordersno");
		allFieldMap.put("stkcode", "stkcode");
		allFieldMap.put("stkname", "stkname");
		allFieldMap.put("bsflag", "bsflag");
		allFieldMap.put("matchtype", "matchtype");
		allFieldMap.put("matchprice", "matchprice");
		allFieldMap.put("matchamt", "matchamt");
		allFieldMap.put("secuid", "secuid");
		allFieldMap.put("market", "market");
		allFieldMap.put("inputid", "inputid");
		allFieldMap.put("orderid", "orderid");
		allFieldMap.put("matchqty", "matchqty");
		allFieldMap.put("poststr", "poststr");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(255)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"matchcode","matchcode","");
	public final TableField<Integer> matchcode = new TableFieldImpl<Integer>(this,"matchcode","matchcode","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> ordersno = new TableFieldImpl<String>(this,"ordersno","ordersno","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> stkcode = new TableFieldImpl<String>(this,"stkcode","stkcode","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> stkname = new TableFieldImpl<String>(this,"stkname","stkname","");

	/**
	 *  | varchar(2)
	 */
	public final TableField<String> bsflag = new TableFieldImpl<String>(this,"bsflag","bsflag","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> matchtype = new TableFieldImpl<String>(this,"matchtype","matchtype","");

	/**
	 *  | decimal(10,4)
	 */
	public final TableField<Double> matchprice = new TableFieldImpl<Double>(this,"matchprice","matchprice","");

	/**
	 *  | decimal(16,4)
	 */
	public final TableField<Double> matchamt = new TableFieldImpl<Double>(this,"matchamt","matchamt","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> secuid = new TableFieldImpl<String>(this,"secuid","secuid","");

	/**
	 *  | varchar(1)
	 */
	public final TableField<String> market = new TableFieldImpl<String>(this,"market","market","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> inputid = new TableFieldImpl<String>(this,"inputid","inputid","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> orderid = new TableFieldImpl<String>(this,"orderid","orderid","");

	/**
	 *  | decimal(16,0)
	 */
	public final TableField<Double> matchqty = new TableFieldImpl<Double>(this,"matchqty","matchqty","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> poststr = new TableFieldImpl<String>(this,"poststr","poststr","");

	private final TableField<?>[] allFields = new TableField<?>[] {matchcode,ordersno,stkcode,stkname,bsflag,matchtype,matchprice,matchamt,secuid,market,inputid,orderid,matchqty,poststr};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TStkTodayCfm[table=stk_today_cfm]";
	}
}
