package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TStkServerTqType extends AbstractTable {

	static {
		init();
	}

	private TStkServerTqType(){
		super.tableName = "stk_server_tq_type";
	}

	private TStkServerTqType(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TStkServerTqType getInstance() {
		return new TStkServerTqType();
	}

	public static final TStkServerTqType getInstance(String aliasName) {
		return new TStkServerTqType(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("extractType", "extract_type");
		allFieldMap.put("extractCode", "extract_code");
		allFieldMap.put("extractHb", "extract_hb");
		allFieldMap.put("extractHbCode", "extract_hb_code");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 提取方式 | varchar(20)
	 */
	public final TableField<String> extractType = new TableFieldImpl<String>(this,"extract_type","extractType","提取方式");

	/**
	 * 提取方式代码 | varchar(10)
	 */
	public final TableField<String> extractCode = new TableFieldImpl<String>(this,"extract_code","extractCode","提取方式代码");

	/**
	 * 提取货币方式(美元,港币) | varchar(10)
	 */
	public final TableField<String> extractHb = new TableFieldImpl<String>(this,"extract_hb","extractHb","提取货币方式(美元,港币)");

	/**
	 * 提取货币方式代码 | bigint(5)
	 */
	public final TableField<Long> extractHbCode = new TableFieldImpl<Long>(this,"extract_hb_code","extractHbCode","提取货币方式代码");

	/**
	 * 创建时间 | date
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | date
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {id,extractType,extractCode,extractHb,extractHbCode,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TStkServerTqType[table=stk_server_tq_type]";
	}
}
