package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TStsDayActiUser extends AbstractTable {

	static {
		init();
	}

	private TStsDayActiUser(){
		super.tableName = "sts_day_acti_user";
	}

	private TStsDayActiUser(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TStsDayActiUser getInstance() {
		return new TStsDayActiUser();
	}

	public static final TStsDayActiUser getInstance(String aliasName) {
		return new TStsDayActiUser(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("dayActiId", "day_acti_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("createTime", "create_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | int(20) unsigned
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"day_acti_id","dayActiId","主键");
	public final TableField<Integer> dayActiId = new TableFieldImpl<Integer>(this,"day_acti_id","dayActiId","主键");

	/**
	 * 用户id | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * 创建时间，用户使用设备的最新时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间，用户使用设备的最新时间");

	private final TableField<?>[] allFields = new TableField<?>[] {dayActiId,userId,createTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TStsDayActiUser[table=sts_day_acti_user]";
	}
}
