package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSysMsg extends AbstractTable {

	static {
		init();
	}

	private TSysMsg(){
		super.tableName = "sys_msg";
	}

	private TSysMsg(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSysMsg getInstance() {
		return new TSysMsg();
	}

	public static final TSysMsg getInstance(String aliasName) {
		return new TSysMsg(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("msgId", "msg_id");
		allFieldMap.put("msgGroup", "msg_group");
		allFieldMap.put("targetId", "target_id");
		allFieldMap.put("msgType", "msg_type");
		allFieldMap.put("msgLevel", "msg_level");
		allFieldMap.put("msgTitle", "msg_title");
		allFieldMap.put("msgContent", "msg_content");
		allFieldMap.put("url", "url");
		allFieldMap.put("updVersion", "upd_version");
		allFieldMap.put("oprId", "opr_id");
		allFieldMap.put("oprName", "opr_name");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 消息id | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"msg_id","msgId","消息id");
	public final TableField<Integer> msgId = new TableFieldImpl<Integer>(this,"msg_id","msgId","消息id");

	/**
	 * 消息分组(P-个人,A-全站) | char(1)
	 */
	public final TableField<String> msgGroup = new TableFieldImpl<String>(this,"msg_group","msgGroup","消息分组(P-个人,A-全站)");

	/**
	 * msg_group=P时,记录为用户id;当msg_group=A时,为0 | int(11)
	 */
	public final TableField<Integer> targetId = new TableFieldImpl<Integer>(this,"target_id","targetId","msg_group=P时,记录为用户id;当msg_group=A时,为0");

	/**
	 * 消息类型 | char(1)
	 */
	public final TableField<String> msgType = new TableFieldImpl<String>(this,"msg_type","msgType","消息类型");

	/**
	 * 消息级别(I-重要G-普通) | char(1)
	 */
	public final TableField<String> msgLevel = new TableFieldImpl<String>(this,"msg_level","msgLevel","消息级别(I-重要G-普通)");

	/**
	 *  | varchar(100)
	 */
	public final TableField<String> msgTitle = new TableFieldImpl<String>(this,"msg_title","msgTitle","");

	/**
	 *  | varchar(2000)
	 */
	public final TableField<String> msgContent = new TableFieldImpl<String>(this,"msg_content","msgContent","");

	/**
	 *  | varchar(100)
	 */
	public final TableField<String> url = new TableFieldImpl<String>(this,"url","url","");

	/**
	 * 更新版本号 | bigint(19)
	 */
	public final TableField<Long> updVersion = new TableFieldImpl<Long>(this,"upd_version","updVersion","更新版本号");

	/**
	 * 操作人id | int(11)
	 */
	public final TableField<Integer> oprId = new TableFieldImpl<Integer>(this,"opr_id","oprId","操作人id");

	/**
	 *  | varchar(30)
	 */
	public final TableField<String> oprName = new TableFieldImpl<String>(this,"opr_name","oprName","");

	/**
	 * 是否有效0-无效，1-有效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","是否有效0-无效，1-有效");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	private final TableField<?>[] allFields = new TableField<?>[] {msgId,msgGroup,targetId,msgType,msgLevel,msgTitle,msgContent,url,updVersion,oprId,oprName,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSysMsg[table=sys_msg]";
	}
}
