package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;

public class TSysCity extends AbstractTable {

	static {
		init();
	}

	private TSysCity(){
		super.tableName = "sys_city";
	}

	private TSysCity(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSysCity getInstance() {
		return new TSysCity();
	}

	public static final TSysCity getInstance(String aliasName) {
		return new TSysCity(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("name", "name");
		allFieldMap.put("provinceId", "province_id");
		allFieldMap.put("keyTitle", "key_title");
		allFieldMap.put("status", "status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 * 城市名称 | char(255)
	 */
	public final TableField<String> name = new TableFieldImpl<String>(this,"name","name","城市名称");

	/**
	 * 所属省份 | int(11)
	 */
	public final TableField<Integer> provinceId = new TableFieldImpl<Integer>(this,"province_id","provinceId","所属省份");

	/**
	 * 拼音首字符 | char(255)
	 */
	public final TableField<String> keyTitle = new TableFieldImpl<String>(this,"key_title","keyTitle","拼音首字符");

	/**
	 * 是否有效，1为有效，0未无效 | int(1)
	 */
	public final TableField<Integer> status = new TableFieldImpl<Integer>(this,"status","status","是否有效，1为有效，0未无效");

	private final TableField<?>[] allFields = new TableField<?>[] {id,name,provinceId,keyTitle,status};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSysCity[table=sys_city]";
	}
}
