package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TSysSensitiveWord extends AbstractTable {

	static {
		init();
	}

	private TSysSensitiveWord(){
		super.tableName = "sys_sensitive_word";
	}

	private TSysSensitiveWord(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TSysSensitiveWord getInstance() {
		return new TSysSensitiveWord();
	}

	public static final TSysSensitiveWord getInstance(String aliasName) {
		return new TSysSensitiveWord(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("wordId", "word_id");
		allFieldMap.put("type", "type");
		allFieldMap.put("word", "word");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updVersion", "upd_version");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(20) unsigned zerofill
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"word_id","wordId","");
	public final TableField<Integer> wordId = new TableFieldImpl<Integer>(this,"word_id","wordId","");

	/**
	 * 类型，1昵称，2言论 | tinyint(4)
	 */
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","类型，1昵称，2言论");

	/**
	 * 敏感词 | varchar(50)
	 */
	public final TableField<String> word = new TableFieldImpl<String>(this,"word","word","敏感词");

	/**
	 * 是否有效（默认1有效，0无效） | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","是否有效（默认1有效，0无效）");

	/**
	 * 记录创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","记录创建时间");

	/**
	 * 修改版本号 | int(11)
	 */
	public final TableField<Integer> updVersion = new TableFieldImpl<Integer>(this,"upd_version","updVersion","修改版本号");

	/**
	 * 记录修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","记录修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {wordId,type,word,isStatus,createTime,updVersion,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TSysSensitiveWord[table=sys_sensitive_word]";
	}
}
