package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserThirdpartyInfo extends AbstractTable {

	static {
		init();
	}

	private TUserThirdpartyInfo(){
		super.tableName = "user_thirdparty_info";
	}

	private TUserThirdpartyInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserThirdpartyInfo getInstance() {
		return new TUserThirdpartyInfo();
	}

	public static final TUserThirdpartyInfo getInstance(String aliasName) {
		return new TUserThirdpartyInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("nickName", "nick_name");
		allFieldMap.put("headImgUrl", "head_img_url");
		allFieldMap.put("sex", "sex");
		allFieldMap.put("address", "address");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("accountNo", "account_no");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> nickName = new TableFieldImpl<String>(this,"nick_name","nickName","");

	/**
	 *  | varchar(250)
	 */
	public final TableField<String> headImgUrl = new TableFieldImpl<String>(this,"head_img_url","headImgUrl","");

	/**
	 *  | int(5)
	 */
	public final TableField<Integer> sex = new TableFieldImpl<Integer>(this,"sex","sex","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> address = new TableFieldImpl<String>(this,"address","address","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | varchar(32)
	 */
	public final TableField<String> accountNo = new TableFieldImpl<String>(this,"account_no","accountNo","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,nickName,headImgUrl,sex,address,createTime,accountNo,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserThirdpartyInfo[table=user_thirdparty_info]";
	}
}
