package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserContact extends AbstractTable {

	static {
		init();
	}

	private TUserContact(){
		super.tableName = "user_contact";
	}

	private TUserContact(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserContact getInstance() {
		return new TUserContact();
	}

	public static final TUserContact getInstance(String aliasName) {
		return new TUserContact(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("contactId", "contact_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("certType", "cert_type");
		allFieldMap.put("certCode", "cert_code");
		allFieldMap.put("relaName", "rela_name");
		allFieldMap.put("deviceId", "device_id");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 关系链ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"contact_id","contactId","关系链ID");
	public final TableField<Integer> contactId = new TableFieldImpl<Integer>(this,"contact_id","contactId","关系链ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 凭证类型(0-手机,1-邮箱,2-微信,3-微博,4-QQ) | tinyint(4)
	 */
	public final TableField<Integer> certType = new TableFieldImpl<Integer>(this,"cert_type","certType","凭证类型(0-手机,1-邮箱,2-微信,3-微博,4-QQ)");

	/**
	 *  | varchar(100)
	 */
	public final TableField<String> certCode = new TableFieldImpl<String>(this,"cert_code","certCode","");

	/**
	 *  | varchar(500)
	 */
	public final TableField<String> relaName = new TableFieldImpl<String>(this,"rela_name","relaName","");

	/**
	 *  | int(11)
	 */
	public final TableField<Integer> deviceId = new TableFieldImpl<Integer>(this,"device_id","deviceId","");

	/**
	 * 记录状态(0-无效，默认1-有效) | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态(0-无效，默认1-有效)");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 最后修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","最后修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {contactId,userId,certType,certCode,relaName,deviceId,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserContact[table=user_contact]";
	}
}
