package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserChannelInfo extends AbstractTable {

	static {
		init();
	}

	private TUserChannelInfo(){
		super.tableName = "user_channel_info";
	}

	private TUserChannelInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserChannelInfo getInstance() {
		return new TUserChannelInfo();
	}

	public static final TUserChannelInfo getInstance(String aliasName) {
		return new TUserChannelInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("channelId", "channel_id");
		allFieldMap.put("channelName", "channel_name");
		allFieldMap.put("companyName", "company_name");
		allFieldMap.put("accessPoint", "access_point");
		allFieldMap.put("diversMode", "divers_mode");
		allFieldMap.put("regisUserSize", "regis_user_size");
		allFieldMap.put("rmk", "rmk");
		allFieldMap.put("createBy", "create_by");
		allFieldMap.put("updateBy", "update_by");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 记录ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","记录ID");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","记录ID");

	/**
	 * 渠道ID | varchar(20)
	 */
	public final TableField<String> channelId = new TableFieldImpl<String>(this,"channel_id","channelId","渠道ID");

	/**
	 * 渠道名称 | varchar(50)
	 */
	public final TableField<String> channelName = new TableFieldImpl<String>(this,"channel_name","channelName","渠道名称");

	/**
	 * 公司名称 | varchar(100)
	 */
	public final TableField<String> companyName = new TableFieldImpl<String>(this,"company_name","companyName","公司名称");

	/**
	 * 预计接入点(1:首批) | varchar(30)
	 */
	public final TableField<String> accessPoint = new TableFieldImpl<String>(this,"access_point","accessPoint","预计接入点(1:首批)");

	/**
	 * 导流方式（1:线上，2:线下） | varchar(30)
	 */
	public final TableField<String> diversMode = new TableFieldImpl<String>(this,"divers_mode","diversMode","导流方式（1:线上，2:线下）");

	/**
	 * 注册用户规模 | int(11)
	 */
	public final TableField<Integer> regisUserSize = new TableFieldImpl<Integer>(this,"regis_user_size","regisUserSize","注册用户规模");

	/**
	 * 备注 | varchar(300)
	 */
	public final TableField<String> rmk = new TableFieldImpl<String>(this,"rmk","rmk","备注");

	/**
	 * 创建人 | varchar(50)
	 */
	public final TableField<String> createBy = new TableFieldImpl<String>(this,"create_by","createBy","创建人");

	/**
	 * 修改人 | varchar(50)
	 */
	public final TableField<String> updateBy = new TableFieldImpl<String>(this,"update_by","updateBy","修改人");

	/**
	 * 创建日期 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建日期");

	/**
	 * 修改日期 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改日期");

	private final TableField<?>[] allFields = new TableField<?>[] {id,channelId,channelName,companyName,accessPoint,diversMode,regisUserSize,rmk,createBy,updateBy,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserChannelInfo[table=user_channel_info]";
	}
}
