package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserOpenAccountData extends AbstractTable {

	static {
		init();
	}

	private TUserOpenAccountData(){
		super.tableName = "user_open_account_data";
	}

	private TUserOpenAccountData(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserOpenAccountData getInstance() {
		return new TUserOpenAccountData();
	}

	public static final TUserOpenAccountData getInstance(String aliasName) {
		return new TUserOpenAccountData(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("clientId", "client_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("applyDate", "apply_date");
		allFieldMap.put("fillDataDate", "fill_data_date");
		allFieldMap.put("witnessDate", "witness_date");
		allFieldMap.put("openDate", "open_date");
		allFieldMap.put("activeDate", "active_date");
		allFieldMap.put("clientSelfSwitch", "client_self_switch");
		allFieldMap.put("isReward", "isReward");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 * 客户号（交易帐号） | varchar(20)
	 */
	public final TableField<String> clientId = new TableFieldImpl<String>(this,"client_id","clientId","客户号（交易帐号）");

	/**
	 * 犇犇号 | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","犇犇号");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> applyDate = new DateTableFieldImpl<Date>(this,"apply_date","applyDate","创建时间");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> fillDataDate = new DateTableFieldImpl<Date>(this,"fill_data_date","fillDataDate","");

	/**
	 * 见证时间 | datetime
	 */
	public final DateTableField<Date> witnessDate = new DateTableFieldImpl<Date>(this,"witness_date","witnessDate","见证时间");

	/**
	 * 开户时间 | datetime
	 */
	public final DateTableField<Date> openDate = new DateTableFieldImpl<Date>(this,"open_date","openDate","开户时间");

	/**
	 * 激活时间 | datetime
	 */
	public final DateTableField<Date> activeDate = new DateTableFieldImpl<Date>(this,"active_date","activeDate","激活时间");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> clientSelfSwitch = new TableFieldImpl<String>(this,"client_self_switch","clientSelfSwitch","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isReward = new TableFieldImpl<Boolean>(this,"isReward","isReward","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,clientId,userId,applyDate,fillDataDate,witnessDate,openDate,activeDate,clientSelfSwitch,isReward,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserOpenAccountData[table=user_open_account_data]";
	}
}
