package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserInfoExtend extends AbstractTable {

	static {
		init();
	}

	private TUserInfoExtend(){
		super.tableName = "user_info_extend";
	}

	private TUserInfoExtend(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserInfoExtend getInstance() {
		return new TUserInfoExtend();
	}

	public static final TUserInfoExtend getInstance(String aliasName) {
		return new TUserInfoExtend(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userExtendId", "user_extend_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("cityId", "city_id");
		allFieldMap.put("assetSize", "asset_size");
		allFieldMap.put("investType", "invest_type");
		allFieldMap.put("listenHabits", "listen_habits");
		allFieldMap.put("analysisType", "analysis_type");
		allFieldMap.put("assetIds", "asset_ids");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(20)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"user_extend_id","userExtendId","");
	public final TableField<Integer> userExtendId = new TableFieldImpl<Integer>(this,"user_extend_id","userExtendId","");

	/**
	 * 用户id | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户id");

	/**
	 * 城市id | int(11)
	 */
	public final TableField<Integer> cityId = new TableFieldImpl<Integer>(this,"city_id","cityId","城市id");

	/**
	 * 资产规模 | varchar(15)
	 */
	public final TableField<String> assetSize = new TableFieldImpl<String>(this,"asset_size","assetSize","资产规模");

	/**
	 * 投资喜好 | varchar(15)
	 */
	public final TableField<String> investType = new TableFieldImpl<String>(this,"invest_type","investType","投资喜好");

	/**
	 * 听消息习惯 | varchar(15)
	 */
	public final TableField<String> listenHabits = new TableFieldImpl<String>(this,"listen_habits","listenHabits","听消息习惯");

	/**
	 * 分析类型 | varchar(15)
	 */
	public final TableField<String> analysisType = new TableFieldImpl<String>(this,"analysis_type","analysisType","分析类型");

	/**
	 * 资产id数组 | varchar(500)
	 */
	public final TableField<String> assetIds = new TableFieldImpl<String>(this,"asset_ids","assetIds","资产id数组");

	/**
	 * 记录状态 0-无效，默认1-有效  | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态 0-无效，默认1-有效 ");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {userExtendId,userId,cityId,assetSize,investType,listenHabits,analysisType,assetIds,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserInfoExtend[table=user_info_extend]";
	}
}
