package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserMyFav extends AbstractTable {

	static {
		init();
	}

	private TUserMyFav(){
		super.tableName = "user_my_fav";
	}

	private TUserMyFav(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserMyFav getInstance() {
		return new TUserMyFav();
	}

	public static final TUserMyFav getInstance(String aliasName) {
		return new TUserMyFav(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userMyFavId", "user_my_fav_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("title", "title");
		allFieldMap.put("busiTabName", "busi_tab_name");
		allFieldMap.put("busiPkId", "busi_pk_id");
		allFieldMap.put("url", "url");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isStatus", "is_status");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"user_my_fav_id","userMyFavId","主键ID");
	public final TableField<Integer> userMyFavId = new TableFieldImpl<Integer>(this,"user_my_fav_id","userMyFavId","主键ID");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 标题 | varchar(255)
	 */
	public final TableField<String> title = new TableFieldImpl<String>(this,"title","title","标题");

	/**
	 * 收藏对象对应的表名 | varchar(255)
	 */
	public final TableField<String> busiTabName = new TableFieldImpl<String>(this,"busi_tab_name","busiTabName","收藏对象对应的表名");

	/**
	 * 收藏对象对应的表主键 | varchar(255)
	 */
	public final TableField<String> busiPkId = new TableFieldImpl<String>(this,"busi_pk_id","busiPkId","收藏对象对应的表主键");

	/**
	 * url | varchar(2000)
	 */
	public final TableField<String> url = new TableFieldImpl<String>(this,"url","url","url");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 记录是否有效，1有效，0无效 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录是否有效，1有效，0无效");

	private final TableField<?>[] allFields = new TableField<?>[] {userMyFavId,userId,title,busiTabName,busiPkId,url,createTime,updateTime,isStatus};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserMyFav[table=user_my_fav]";
	}
}
