package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserStat extends AbstractTable {

	static {
		init();
	}

	private TUserStat(){
		super.tableName = "user_stat";
	}

	private TUserStat(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserStat getInstance() {
		return new TUserStat();
	}

	public static final TUserStat getInstance(String aliasName) {
		return new TUserStat(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("hisHldCount", "his_hld_count");
		allFieldMap.put("hisHldWon", "his_hld_won");
		allFieldMap.put("hisHldDay", "his_hld_day");
		allFieldMap.put("maxRetracement", "max_retracement");
		allFieldMap.put("maxRetracementHigh", "max_retracement_high");
		allFieldMap.put("maxRetracementLow", "max_retracement_low");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","用户ID");

	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 历史持仓的个股数量 | int(11)
	 */
	public final TableField<Integer> hisHldCount = new TableFieldImpl<Integer>(this,"his_hld_count","hisHldCount","历史持仓的个股数量");

	/**
	 * 历史持仓盈利的个股数量 | int(11)
	 */
	public final TableField<Integer> hisHldWon = new TableFieldImpl<Integer>(this,"his_hld_won","hisHldWon","历史持仓盈利的个股数量");

	/**
	 * 历史平均持股天数 | decimal(6,1)
	 */
	public final TableField<BigDecimal> hisHldDay = new TableFieldImpl<BigDecimal>(this,"his_hld_day","hisHldDay","历史平均持股天数");

	/**
	 * 最大回撤 | decimal(10,4)
	 */
	public final TableField<BigDecimal> maxRetracement = new TableFieldImpl<BigDecimal>(this,"max_retracement","maxRetracement","最大回撤");

	/**
	 * 最大回测最高点日期 | date
	 */
	public final DateTableField<Date> maxRetracementHigh = new DateTableFieldImpl<Date>(this,"max_retracement_high","maxRetracementHigh","最大回测最高点日期");

	/**
	 * 最大回测最低点日期 | date
	 */
	public final DateTableField<Date> maxRetracementLow = new DateTableFieldImpl<Date>(this,"max_retracement_low","maxRetracementLow","最大回测最低点日期");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 更新时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","更新时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {userId,hisHldCount,hisHldWon,hisHldDay,maxRetracement,maxRetracementHigh,maxRetracementLow,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TUserStat[table=user_stat]";
	}
}
