package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserChannel extends AbstractTable {

	static {
		init();
	}

	private TUserChannel(){
		super.tableName = "user_channel";
	}

	private TUserChannel(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserChannel getInstance() {
		return new TUserChannel();
	}

	public static final TUserChannel getInstance(String aliasName) {
		return new TUserChannel(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("userChannelId", "user_channel_id");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("channelId", "channel_id");
		allFieldMap.put("qnOpenid", "qn_openid");
		allFieldMap.put("outOpenid", "out_openid");
		allFieldMap.put("currentStatus", "current_status");
		allFieldMap.put("bindTime", "bind_time");
		allFieldMap.put("cancelTime", "cancel_time");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("lockVersion", "lock_version");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 用户交易渠道ID;非自增长ID（以便根据本字段生成齐牛OPENID，一次性入库） | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"user_channel_id","userChannelId","用户交易渠道ID;非自增长ID（以便根据本字段生成齐牛OPENID，一次性入库）");

	/**
	 * 乐观锁字段
	 */
	public final TableField<Integer>  lock = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","用户交易渠道ID;非自增长ID（以便根据本字段生成齐牛OPENID，一次性入库）");

	public final TableField<Integer> userChannelId = new TableFieldImpl<Integer>(this,"user_channel_id","userChannelId","用户交易渠道ID;非自增长ID（以便根据本字段生成齐牛OPENID，一次性入库）");

	/**
	 * 用户ID | int(11)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","用户ID");

	/**
	 * 渠道ID;如iTN、国信直连、广发直连等 | int(11)
	 */
	public final TableField<Integer> channelId = new TableFieldImpl<Integer>(this,"channel_id","channelId","渠道ID;如iTN、国信直连、广发直连等");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> qnOpenid = new TableFieldImpl<String>(this,"qn_openid","qnOpenid","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> outOpenid = new TableFieldImpl<String>(this,"out_openid","outOpenid","");

	/**
	 * 当前状态;N-未绑定（仅生成qn_openid）,B-已绑定,C-已解绑 | char(1)
	 */
	public final TableField<String> currentStatus = new TableFieldImpl<String>(this,"current_status","currentStatus","当前状态;N-未绑定（仅生成qn_openid）,B-已绑定,C-已解绑");

	/**
	 * 绑定时间 | datetime
	 */
	public final DateTableField<Date> bindTime = new DateTableFieldImpl<Date>(this,"bind_time","bindTime","绑定时间");

	/**
	 * 解绑时间 | datetime
	 */
	public final DateTableField<Date> cancelTime = new DateTableFieldImpl<Date>(this,"cancel_time","cancelTime","解绑时间");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 乐观锁版本号 | int(11)
	 */
	public final TableField<Integer> lockVersion = new TableFieldImpl<Integer>(this,"lock_version","lockVersion","乐观锁版本号");

	private final TableField<?>[] allFields = new TableField<?>[] {userChannelId,userId,channelId,qnOpenid,outOpenid,currentStatus,bindTime,cancelTime,createTime,updateTime,lockVersion};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return lock;
	}

	public final boolean isAutoGeneratedPK() {
		return false;
	}

	public final boolean isLockVersion() {
		return true;
	}

	public String toString() {
		return "TUserChannel[table=user_channel]";
	}
}
