package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserChannelConfig extends AbstractTable {

	static {
		init();
	}

	private TUserChannelConfig(){
		super.tableName = "user_channel_config";
	}

	private TUserChannelConfig(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserChannelConfig getInstance() {
		return new TUserChannelConfig();
	}

	public static final TUserChannelConfig getInstance(String aliasName) {
		return new TUserChannelConfig(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("channelId", "channel_id");
		allFieldMap.put("url", "url");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("logo", "logo");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("type", "type");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"id","id","");
	public final TableField<Integer> id = new TableFieldImpl<Integer>(this,"id","id","");

	/**
	 *  | varchar(20)
	 */
	public final TableField<String> channelId = new TableFieldImpl<String>(this,"channel_id","channelId","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> url = new TableFieldImpl<String>(this,"url","url","");

	/**
	 *  | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> logo = new TableFieldImpl<String>(this,"logo","logo","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 * 1:普通 2：定制 | tinyint(4)
	 */
	public final TableField<Integer> type = new TableFieldImpl<Integer>(this,"type","type","1:普通 2：定制");

	private final TableField<?>[] allFields = new TableField<?>[] {id,channelId,url,isStatus,logo,createTime,type};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserChannelConfig[table=user_channel_config]";
	}
}
