package com.minigod.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TUserReq extends AbstractTable {

	static {
		init();
	}

	private TUserReq(){
		super.tableName = "user_req";
	}

	private TUserReq(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TUserReq getInstance() {
		return new TUserReq();
	}

	public static final TUserReq getInstance(String aliasName) {
		return new TUserReq(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("reqId", "req_id");
		allFieldMap.put("certType", "cert_type");
		allFieldMap.put("certCode", "cert_code");
		allFieldMap.put("mobile", "phone");
		allFieldMap.put("dealStatus", "deal_status");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 申请ID | int(11)
	 */
	public final TableField<Integer>  pk = new TableFieldImpl<Integer>(this,"req_id","reqId","申请ID");
	public final TableField<Integer> reqId = new TableFieldImpl<Integer>(this,"req_id","reqId","申请ID");

	/**
	 * 凭证类型2-微信unionid | tinyint(4)
	 */
	public final TableField<Integer> certType = new TableFieldImpl<Integer>(this,"cert_type","certType","凭证类型2-微信unionid");

	/**
	 *  | varchar(100)
	 */
	public final TableField<String> certCode = new TableFieldImpl<String>(this,"cert_code","certCode","");

	/**
	 *  | varchar(15)
	 */
	public final TableField<String> mobile = new TableFieldImpl<String>(this,"phone","phone","");

	/**
	 * 处理结果 | tinyint(4)
	 */
	public final TableField<Integer> dealStatus = new TableFieldImpl<Integer>(this,"deal_status","dealStatus","处理结果");

	/**
	 * 记录状态 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 最后修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","最后修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {reqId,certType,certCode,mobile,dealStatus,isStatus,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TUserReq[table=user_req]";
	}
}
