package com.minigod.broker.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TBrokerUserThirdInfo extends AbstractTable {

	static {
		init();
	}

	private TBrokerUserThirdInfo(){
		super.tableName = "broker_user_third_info";
	}

	private TBrokerUserThirdInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TBrokerUserThirdInfo getInstance() {
		return new TBrokerUserThirdInfo();
	}

	public static final TBrokerUserThirdInfo getInstance(String aliasName) {
		return new TBrokerUserThirdInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("bandingId", "banding_id");
		allFieldMap.put("bandingType", "banding_type");
		allFieldMap.put("nickName", "nick_name");
		allFieldMap.put("headImgUrl", "head_img_url");
		allFieldMap.put("sex", "sex");
		allFieldMap.put("address", "address");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 *  | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> bandingId = new TableFieldImpl<String>(this,"banding_id","bandingId","");

	/**
	 * 2:微信openid | int(5)
	 */
	public final TableField<Integer> bandingType = new TableFieldImpl<Integer>(this,"banding_type","bandingType","2:微信openid");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> nickName = new TableFieldImpl<String>(this,"nick_name","nickName","");

	/**
	 *  | varchar(255)
	 */
	public final TableField<String> headImgUrl = new TableFieldImpl<String>(this,"head_img_url","headImgUrl","");

	/**
	 *  | int(5)
	 */
	public final TableField<Integer> sex = new TableFieldImpl<Integer>(this,"sex","sex","");

	/**
	 *  | varchar(50)
	 */
	public final TableField<String> address = new TableFieldImpl<String>(this,"address","address","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","");

	/**
	 *  | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","");

	private final TableField<?>[] allFields = new TableField<?>[] {id,bandingId,bandingType,nickName,headImgUrl,sex,address,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TBrokerUserThirdInfo[table=broker_user_third_info]";
	}
}
