package com.minigod.broker.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TBrokerUserInfo extends AbstractTable {

	static {
		init();
	}

	private TBrokerUserInfo(){
		super.tableName = "broker_user_info";
	}

	private TBrokerUserInfo(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TBrokerUserInfo getInstance() {
		return new TBrokerUserInfo();
	}

	public static final TBrokerUserInfo getInstance(String aliasName) {
		return new TBrokerUserInfo(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("userName", "user_name");
		allFieldMap.put("userIcon", "user_icon");
		allFieldMap.put("phoneNum", "phone_num");
		allFieldMap.put("userStatus", "user_status");
		allFieldMap.put("password", "password");
		allFieldMap.put("isBindWx", "is_bind_wx");
		allFieldMap.put("wxOpenId", "wx_open_id");
		allFieldMap.put("pwdErrorCount", "pwd_error_count");
		allFieldMap.put("lockTime", "lock_time");
		allFieldMap.put("isSign", "is_sign");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"broker_id","brokerId","主键");
	public final TableField<Long> brokerId = new TableFieldImpl<Long>(this,"broker_id","brokerId","主键");

	/**
	 * 帐户名 | varchar(20)
	 */
	public final TableField<String> userName = new TableFieldImpl<String>(this,"user_name","userName","帐户名");

	/**
	 * 用户图像 | varchar(200)
	 */
	public final TableField<String> userIcon = new TableFieldImpl<String>(this,"user_icon","userIcon","用户图像");

	/**
	 * 手机号 | varchar(20)
	 */
	public final TableField<String> phoneNum = new TableFieldImpl<String>(this,"phone_num","phoneNum","手机号");

	/**
	 * 用户状态 0-停用,1-正常,2-锁定 | tinyint(4)
	 */
	public final TableField<Integer> userStatus = new TableFieldImpl<Integer>(this,"user_status","userStatus","用户状态 0-停用,1-正常,2-锁定");

	/**
	 * 密码 | varchar(100)
	 */
	public final TableField<String> password = new TableFieldImpl<String>(this,"password","password","密码");

	/**
	 * 是否绑定微信 | tinyint(1)
	 */
	public final TableField<Boolean> isBindWx = new TableFieldImpl<Boolean>(this,"is_bind_wx","isBindWx","是否绑定微信");

	/**
	 * 微信openid | varchar(500)
	 */
	public final TableField<String> wxOpenId = new TableFieldImpl<String>(this,"wx_open_id","wxOpenId","微信openid");

	/**
	 * 密码错误次数 | tinyint(4)
	 */
	public final TableField<Integer> pwdErrorCount = new TableFieldImpl<Integer>(this,"pwd_error_count","pwdErrorCount","密码错误次数");

	/**
	 * 用户密码锁定的时间 | datetime
	 */
	public final DateTableField<Date> lockTime = new DateTableFieldImpl<Date>(this,"lock_time","lockTime","用户密码锁定的时间");

	/**
	 * 是否签约经理人 | tinyint(1)
	 */
	public final TableField<Boolean> isSign = new TableFieldImpl<Boolean>(this,"is_sign","isSign","是否签约经理人");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {brokerId,userName,userIcon,phoneNum,userStatus,password,isBindWx,wxOpenId,pwdErrorCount,lockTime,isSign,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TBrokerUserInfo[table=broker_user_info]";
	}
}
