package com.minigod.broker.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TBrokerAccountCollocation extends AbstractTable {

	static {
		init();
	}

	private TBrokerAccountCollocation(){
		super.tableName = "broker_account_collocation";
	}

	private TBrokerAccountCollocation(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TBrokerAccountCollocation getInstance() {
		return new TBrokerAccountCollocation();
	}

	public static final TBrokerAccountCollocation getInstance(String aliasName) {
		return new TBrokerAccountCollocation(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("id", "id");
		allFieldMap.put("tradeAccount", "trade_account");
		allFieldMap.put("userId", "user_id");
		allFieldMap.put("stockCode", "stock_code");
		allFieldMap.put("stockName", "stock_name");
		allFieldMap.put("initDate", "init_date");
		allFieldMap.put("tradingVolume", "trading_volume");
		allFieldMap.put("tradingAmount", "trading_amount");
		allFieldMap.put("tradingType", "trading_type");
		allFieldMap.put("currency", "currency");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 主键 | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"id","id","主键");
	public final TableField<Long> id = new TableFieldImpl<Long>(this,"id","id","主键");

	/**
	 * 交易账号 | varchar(100)
	 */
	public final TableField<String> tradeAccount = new TableFieldImpl<String>(this,"trade_account","tradeAccount","交易账号");

	/**
	 * 犇犇号 | int(20)
	 */
	public final TableField<Integer> userId = new TableFieldImpl<Integer>(this,"user_id","userId","犇犇号");

	/**
	 * 证券代码 | varchar(200)
	 */
	public final TableField<String> stockCode = new TableFieldImpl<String>(this,"stock_code","stockCode","证券代码");

	/**
	 * 证券名称 | varchar(500)
	 */
	public final TableField<String> stockName = new TableFieldImpl<String>(this,"stock_name","stockName","证券名称");

	/**
	 * 转仓日期 | date
	 */
	public final DateTableField<Date> initDate = new DateTableFieldImpl<Date>(this,"init_date","initDate","转仓日期");

	/**
	 * 成交数量 | int(50)
	 */
	public final TableField<Integer> tradingVolume = new TableFieldImpl<Integer>(this,"trading_volume","tradingVolume","成交数量");

	/**
	 * 成交金额 | decimal(20,5)
	 */
	public final TableField<BigDecimal> tradingAmount = new TableFieldImpl<BigDecimal>(this,"trading_amount","tradingAmount","成交金额");

	/**
	 * 转入转出类别 | int(2)
	 */
	public final TableField<String> tradingType = new TableFieldImpl<String>(this,"trading_type","tradingType","转入转出类别");

	/**
	 * 货币名称 | varchar(10)
	 */
	public final TableField<String> currency = new TableFieldImpl<String>(this,"currency","currency","货币名称");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	private final TableField<?>[] allFields = new TableField<?>[] {id,tradeAccount,userId,stockCode,stockName,initDate,tradingVolume,tradingAmount,tradingType,currency,createTime,updateTime};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TBrokerAccountCollocation[table=broker_account_collocation]";
	}
}
