package com.minigod.broker.persist.tables;
import com.minigod.db4j.table.AllField;
import com.minigod.db4j.table.AbstractTable;
import com.minigod.db4j.table.TableField;
import com.minigod.db4j.table.TableFieldImpl;
import java.util.HashMap;
import java.util.Map;
import java.math.BigDecimal;
import java.util.Date;
import com.minigod.db4j.table.DateTableField;
import com.minigod.db4j.table.DateTableFieldImpl;

public class TBrokerCashAcc extends AbstractTable {

	static {
		init();
	}

	private TBrokerCashAcc(){
		super.tableName = "broker_cash_acc";
	}

	private TBrokerCashAcc(String aliasName){
		this();
		setAliasName(aliasName);
	}

	public static final TBrokerCashAcc getInstance() {
		return new TBrokerCashAcc();
	}

	public static final TBrokerCashAcc getInstance(String aliasName) {
		return new TBrokerCashAcc(aliasName);
	}

	private static Map<String, String> allFieldMap;
	private static final void init() {
		allFieldMap = new HashMap<String, String>();
		allFieldMap.put("accountId", "account_id");
		allFieldMap.put("brokerId", "broker_id");
		allFieldMap.put("accName", "acc_name");
		allFieldMap.put("ccy", "ccy");
		allFieldMap.put("balance", "balance");
		allFieldMap.put("addBalance", "add_balance");
		allFieldMap.put("addRiskBalance", "add_risk_balance");
		allFieldMap.put("riskBalance", "risk_balance");
		allFieldMap.put("isStatus", "is_status");
		allFieldMap.put("createTime", "create_time");
		allFieldMap.put("updateTime", "update_time");
		allFieldMap.put("isWith", "is_with");
	}

	public String getFieldName(String javaFieldName) {
		return allFieldMap.get(javaFieldName);
	}

	public final TableField<Integer> all = new AllField<Integer>(this,  "*",null);

	public TableField<?> allField() {
		return all;
	}

	/**
	 * 账户ID | bigint(20)
	 */
	public final TableField<Long>  pk = new TableFieldImpl<Long>(this,"account_id","accountId","账户ID");
	public final TableField<Long> accountId = new TableFieldImpl<Long>(this,"account_id","accountId","账户ID");

	/**
	 * 关联账户 | bigint(20)
	 */
	public final TableField<Long> brokerId = new TableFieldImpl<Long>(this,"broker_id","brokerId","关联账户");

	/**
	 * 账户名称及描述 | varchar(50)
	 */
	public final TableField<String> accName = new TableFieldImpl<String>(this,"acc_name","accName","账户名称及描述");

	/**
	 * 币种 | char(3)
	 */
	public final TableField<String> ccy = new TableFieldImpl<String>(this,"ccy","ccy","币种");

	/**
	 * 扣除风险金和提现后的账户余额 | decimal(16,2)
	 */
	public final TableField<BigDecimal> balance = new TableFieldImpl<BigDecimal>(this,"balance","balance","扣除风险金和提现后的账户余额");

	/**
	 * 新增收益 | decimal(16,2)
	 */
	public final TableField<BigDecimal> addBalance = new TableFieldImpl<BigDecimal>(this,"add_balance","addBalance","新增收益");

	/**
	 * 新增收益的风险金 | decimal(16,2)
	 */
	public final TableField<BigDecimal> addRiskBalance = new TableFieldImpl<BigDecimal>(this,"add_risk_balance","addRiskBalance","新增收益的风险金");

	/**
	 * 风险金,收取新增收益的10% | decimal(16,2)
	 */
	public final TableField<BigDecimal> riskBalance = new TableFieldImpl<BigDecimal>(this,"risk_balance","riskBalance","风险金,收取新增收益的10%");

	/**
	 * 记录状态 | tinyint(1)
	 */
	public final TableField<Boolean> isStatus = new TableFieldImpl<Boolean>(this,"is_status","isStatus","记录状态");

	/**
	 * 创建时间 | datetime
	 */
	public final DateTableField<Date> createTime = new DateTableFieldImpl<Date>(this,"create_time","createTime","创建时间");

	/**
	 * 修改时间 | datetime
	 */
	public final DateTableField<Date> updateTime = new DateTableFieldImpl<Date>(this,"update_time","updateTime","修改时间");

	/**
	 * 是否可提现 | tinyint(1)
	 */
	public final TableField<Boolean> isWith = new TableFieldImpl<Boolean>(this,"is_with","isWith","是否可提现");

	private final TableField<?>[] allFields = new TableField<?>[] {accountId,brokerId,accName,ccy,balance,addBalance,addRiskBalance,riskBalance,isStatus,createTime,updateTime,isWith};

	public TableField<?>[] getAllFields() {
		return allFields;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getPK() {
		return pk;
	}

	@SuppressWarnings("unchecked")
	public TableField<?> getLockVersion() {
		return null;
	}

	public final boolean isAutoGeneratedPK() {
		return true;
	}

	public final boolean isLockVersion() {
		return false;
	}

	public String toString() {
		return "TBrokerCashAcc[table=broker_cash_acc]";
	}
}
