spring:
  profiles:
    active: db, redis, notify
  messages:
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8001
  servlet:
    context-path: /notify