# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 7777
  connection-timeout: 1800
  context-path: /cubp

spring:
  # 环境 dev|test|pro
  profiles:
    active: test2

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources: # 静态资源的路径
    static-locations: classpath:/statics/,classpath:/views/
  velocity:
    resource-loader-path: classpath:/template/
    charset: UTF-8

  # Redis配置
  redis:
    database: 0
    #        hostName: 127.0.0.1
    hostName: 10.1.5.110

    port: 6380
    #password:       # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接

  #JSP视图解析器
  # 页面默认前缀目录
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis-config.xml

# APP模块
jwt:
  # token 加密秘钥
  secret: 3733b9170b1e4994bddcf1ce62c4c082
  # token有效时长，7天，单位秒
  expire: 604800
  header: token

security:
  basic:
    enabled: false

# 日志配置
logging:
  config:
    classpath: logback-spring.xml

#activeMQ
activemq:
  broker-url: tcp://10.1.2.99:61616
  user: admin
  password: admin
  #true 表示使用内置的MQ，false则连接服务器
  in-memory: false
  pool:
    #true表示使用连接池；false时，每发送一条数据创建一个连接
    enabled: true
    #连接池最大连接数
    max-connections: 10
    #空闲的连接过期时间，默认为30秒
    idle-timeout: 30000
    #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0
    expiry-timeout: 0