spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.140:3306/opa_main?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username:  root
    password:  zz@123

# Mybatis配置
mybatis:
  mapper-locations: classpath*:com/minigod/persist/*/mapper/impl/*.xml