spring:
  redis:
    database: 0
#    host: 127.0.0.1
    host: 192.168.0.140
#    port: 6379
    #password:       # 密码（默认为空）
    #cluster.max-redirects: 6
    timeout: 20000
    sentinel:
      master: redisMaster
      nodes: 192.168.0.140:26379,192.168.0.140:26380
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-wait: -1
