spring:
  redis:
    database: 3
#    hostName: 127.0.0.1
    hostName: 10.1.2.82
#    port: 6379
    #password:       # 密码（默认为空）
    #cluster.max-redirects: 6
    timeout: 20000
    sentinel:
      master: redisMaster
      nodes: 10.1.2.82:63801,10.1.2.82:63802


    jedis:
      pool:
        max-idle: 20
        max-wait:
        min-idle: 5
