spring:
  redis:
    database: 0
#    hostName: 127.0.0.1
    hostName: 192.168.0.140
#    port: 6379
    #password:       # 密码（默认为空）
    #cluster.max-redirects: 6
    timeout: 20000
    sentinel:
      master: redisMaster
      nodes: 192.168.0.140:26379,192.168.0.140:26380
    pool:
      max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
